INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '1', '¶ PAULO, servo de Jesus Cristo, chamado para apóstolo, separado para o evangelho de Deus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '2', 'O qual antes havia prometido pelos seus profetas nas santas escrituras,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '3', 'Acerca de seu Filho, que nasceu da descendência de David segundo a carne,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '4', 'Declarado Filho de Deus em poder, segundo o Espírito de santificação, pela ressurreição dos mortos - Jesus Cristo, Nosso SENHOR,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '5', 'Pelo qual recebemos a graça e o apostolado, para a obediência da fé entre todas as gentes pelo seu nome,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '6', 'Entre as quais sois também vós chamados para serdes de Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '7', 'A todos os que estais em Roma, amados de Deus, chamados santos: Graça e paz de Deus nosso pai, e do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '8', 'Primeiramente dou graças ao meu Deus por Jesus Cristo, acerca de vós todos, porque em todo o mundo é anunciada a vossa fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '9', 'Porque Deus, a quem sirvo em meu espírito, no evangelho de seu Filho, me é testemunha de como incessantemente faço menção de vós,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '10', 'Pedindo sempre em minhas orações que nalgum tempo, pela vontade de Deus, se me ofereça boa ocasião de ir ter convosco.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '11', 'Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '12', 'Isto é: para que juntamente convosco eu seja consolado pela fé mutua, assim vossa como minha.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '13', 'Não quero porém, irmãos, que ignoreis que muitas vezes propus ir ter convosco (mas até agora tenho sido impedido) para também ter entre vós algum fruto, como também entre os demais gentios.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '14', 'Eu, sou devedor, tanto a gregos como a bárbaros, tanto a sábios como a ignorantes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '15', 'E assim, quanto está em mim, estou pronto para também vos anunciar o evangelho, a vós que estais em Roma.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '16', 'Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê; primeiro do judeu, e também do grego.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '17', 'Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '18', 'Porque do céu se manifesta a ira de Deus sobre toda a impiedade e injustiça dos homens, que detêm a verdade em injustiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '19', 'Porquanto o que de Deus se pode conhecer neles se manifesta, porque Deus lho manifestou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '20', 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder, como a sua divindade, se entendem, e claramente se vêem pelas coisas que estão criadas, para que eles fiquem inescusáveis;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '21', 'Porquanto, tendo conhecido a Deus, não o glorificaram como Deus, nem lhe deram graças, antes em seus discursos se desvaneceram, e o seu coração insensato se obscureceu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '22', 'Dizendo-se sábios, tornaram-se loucos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '23', 'E mudaram a glória do Deus incorruptível em semelhança da imagem de homem corruptível, e de aves, e de quadrúpedes, e de répteis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '24', 'Pelo que também Deus os entregou às concupiscências, de seus corações, à imundície, para desonrarem seus corpos entre si;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '25', 'Pois mudaram a verdade de Deus em mentira, e honraram e serviram mais a criatura do que o Criador, que é bendito eternamente. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '26', 'Pelo que Deus os abandonou às paixões infames. Porque até as suas mulheres mudaram o uso natural, no contrário à natureza.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '27', 'E, semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para com os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a recompensa que convinha ao seu erro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '28', 'E, como eles se não importaram de ter conhecimento de Deus, assim Deus os entregou a um sentimento perverso, para fazerem coisas que não convêm;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '29', 'Estando cheios de toda a iniquidade, prostituição, malícia, avareza, maldade, cheios de inveja, homicídio, contenda, engano, malignidade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '30', 'Sendo murmuradores, detractores, aborrecedores de Deus, injuriadores, soberbos, presunçosos, inventores de males, desobedientes aos pais e às mães;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '31', 'Néscios, infiéis nos contratos, sem afeição natural, irreconciliáveis, sem misericórdia;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '1', '32', 'Os quais, conhecendo a justiça de Deus (que são dignos de morte os que tais coisas praticam), não somente as fazem, mas também consentem aos que as fazem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '1', 'PORTANTO, és inescusável quando julgas, ó homem quem quer que sejas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu, que julgas, fazes o mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '2', 'E bem sabemos que o juízo de Deus é segundo a verdade sobre os que tais coisas fazem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '3', 'E tu, ó homem, que julgas os que fazem tais coisas, cuidas que, fazendo-as tu, escaparás ao juízo de Deus?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '4', 'Ou desprezas tu as riquezas da sua benignidade, e paciência e longanimidade, ignorando que a benignidade de Deus te leva ao arrependimento?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '5', 'Mas, segundo a tua dureza e teu coração impenitente, entesouras ira para ti no dia da ira e da manifestação do juízo de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '6', 'O qual recompensará cada um segundo as suas obras;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '7', 'A saber: a vida eterna aos que, com perseverança em fazer bem, procuram glória, e honra e incorrupção;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '8', 'Mas a indignação e a ira aos que são contenciosos, e desobedientes à verdade e obedientes à iniquidade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '9', 'Tribulação e angústia sobre toda a alma do homem que obra o mal; primeiramente do judeu e também do grego;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '10', 'Glória, porém, e honra e paz a qualquer que obra o bem; primeiramente ao judeu e também ao grego;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '11', 'Porque, para com Deus, não há acepção de pessoas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '12', 'Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '13', 'Porque os que ouvem a lei não são justos diante de Deus; mas os que praticam a lei hão-de ser justificados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '14', 'Porque, quando os gentios, que não têm lei, fazem naturalmente as coisas que são da lei, não tendo eles lei, para si mesmos são lei;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '15', 'Os quais mostram a obra da lei escrita em seus corações, testificando juntamente a sua consciência, e os seus pensamentos, quer acusando-os, quer defendendo-os;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '16', 'No dia em que Deus há-de julgar os segredos dos homens, por Jesus Cristo, segundo o meu evangelho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '17', 'Eis que tu que tens por sobrenome judeu, e repousas na lei, e te glorias em Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '18', 'E sabes a sua vontade e aprovas as coisas excelentes, sendo instruído por lei;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '19', 'E confias que és guia dos cegos, luz dos que estão em trevas,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '20', 'Instruidor dos néscios, mestre de crianças, que tens a forma da ciência, e da verdade na lei;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '21', 'Tu, pois, que ensinas a outro, não te ensinas a ti mesmo? Tu, que pregas que não se deve furtar, furtas?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '22', 'Tu, que dizes que não se deve adulterar, adulteras? Tu, que abominas os ídolos, cometes sacrilégio?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '23', 'Tu, que te glorias na lei, desonras a Deus pela transgressão da lei?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '24', 'Porque, como está escrito, o nome de Deus é blasfemado entre os gentios por causa de vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '25', 'Porque a circuncisão é, na verdade, proveitosa, se tu guardares a lei; mas, se tu és transgressor da lei, a tua circuncisão se torna em incircuncisão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '26', 'Se, pois, a incircuncisão guardar os preceitos da lei, porventura a incircuncisão não será reputada como circuncisão?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '27', 'E a incircuncisão que por natureza o é, se cumpre a lei, não te julgará porventura a ti, que pela letra e circuncisão és transgressor da lei?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '28', 'Porque não é judeu o que o é exteriormente, nem é circuncisão a que o é exteriormente na carne.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '2', '29', 'Mas é judeu o que o é no interior, e circuncisão a que é do coração, no espírito, não na letra: cujo louvor não provém dos homens, mas de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '1', 'QUAL é logo a vantagem do judeu? Ou qual a utilidade da circuncisão?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '2', 'Muita, em toda a maneira, porque, primeiramente, as palavras de Deus lhe foram confiadas,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '3', 'Pois quê? Se alguns foram incrédulos, a sua incredulidade aniquilará a fidelidade de Deus?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '4', 'De maneira nenhuma; sempre seja Deus verdadeiro, e todo o homem mentiroso; como está escrito: Para que sejas justificado em tuas palavras, e venças quando fores julgado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '5', 'E, se a nossa injustiça for causa da justiça de Deus, que diremos? Porventura será Deus injusto, trazendo ira sobre nós? (Falo como homem),');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '6', 'De maneira nenhuma; doutro modo, como julgará Deus o mundo?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '7', 'Mas, se pela minha mentira abundou mais a verdade de Deus para glória sua, porque sou eu ainda julgado também como pecador?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '8', 'E porque não dizemos (como somos blasfemados, e como alguns dizem que dizemos): Façamos males, para que venham bens? A condenação desses é justa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '9', 'Pois quê? Somos nós mais excelentes? De maneira nenhuma, pois já dantes demonstrámos que, tanto judeus como gregos, todos estão debaixo do pecado;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '10', 'Como está escrito: Não há um justo, nem um sequer.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '11', 'Não há ninguém que entenda; não há ninguém que busque a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '12', 'Todos se extraviaram, e juntamente se fizeram inúteis. Não há quem faça o bem, não há nem um só.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '13', 'A sua garganta é um sepulcro aberto: com as suas línguas tratam enganosamente, peçonha de áspides está debaixo de seus lábios;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '14', 'Cuja boca está cheia de maldição e amargura.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '15', 'Os seus pés são ligeiros para derramar sangue.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '16', 'Em seus caminhos há destruição e miséria;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '17', 'E não conheceram o caminho da paz.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '18', 'Não há temor de Deus diante de seus olhos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '19', 'Ora, nós sabemos que tudo o que a lei diz aos que estão debaixo da lei, o diz, para que toda a boca esteja fechada e todo o mundo seja condenável diante de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '20', 'Por isso nenhuma carne será justificada diante dele pelas obras da lei, porque pela lei vem o conhecimento do pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '21', 'Mas agora se manifestou sem lei a justiça de Deus, tendo o testemunho da lei e dos profetas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '22', 'Isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que crêem; porque não há diferença.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '23', 'Porque todos pecaram e destituídos estão da glória de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '24', 'Sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '25', 'Ao qual Deus propôs para propiciação pela fé no seu sangue, para demonstrar a sua justiça pela remissão dos pecados dantes cometidos, sob a paciência de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '26', 'Para demonstração da sua justiça neste tempo presente, para que ele seja justo e justificador daquele que tem fé em Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '27', 'Onde está logo a jactância? É excluída. Por qual lei? Das obras? Não; mas pela lei da fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '28', 'Concluímos pois que o homem é justificado pela fé sem as obras da lei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '29', 'É porventura Deus somente dos judeus? E não o é também dos gentios? Também dos gentios, certamente,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '30', 'Se Deus é um só, que justifica pela fé a circuncisão, e por meio da fé a incircuncisão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '3', '31', 'Anulamos, pois, a lei pela fé? De maneira nenhuma, antes estabelecemos a lei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '1', 'QUE diremos pois ter alcançado Abraão, nosso pai segundo a carne?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '2', 'Porque, se Abraão foi justificado pelas obras, tem de que se gloriar, mas não diante de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '3', 'Pois, que diz a Escritura? Creu Abraão a Deus, e isso lhe foi imputado como justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '4', 'Ora àquele que faz qualquer obra não lhe é imputado o galardão segundo a graça, mas segundo a dívida.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '5', 'Mas àquele que não pratica, mas crê naquele que justifica o ímpio, a sua fé lhe é imputada como justiça,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '6', 'Assim também David declara bem-aventurado o homem a quem Deus imputa a justiça sem as obras, dizendo:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '7', 'Bem-aventurados aqueles cujas maldades são perdoadas, e cujos pecados são cobertos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '8', 'Bem-aventurado o homem a quem o SENHOR não imputa o pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '9', 'Vem pois esta bem-aventurança sobre a circuncisão somente, ou também sobre a incircuncisão? Porque dizemos que a fé foi imputada como justiça a Abraão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '10', 'Como lhe foi pois imputada? Estando na circuncisão ou na incircuncisão? Não na circuncisão, mas na incircuncisão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '11', 'E recebeu o sinal da circuncisão, selo da justiça da fé quando estava na incircuncisão, para que fosse pai de todos os que crêem, estando eles também na incircuncisão; a fim de que também a justiça lhes seja imputada;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '12', 'E fosse pai da circuncisão, daqueles que não somente são da circuncisão, mas que também andam nas pisadas daquela fé de nosso pai Abraão, que tivera na incircuncisão:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '13', 'Porque a promessa de que havia de ser herdeiro do mundo não foi feita pela lei a Abraão, ou à sua posteridade, mas pela justiça da fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '14', 'Porque, se os que são da lei são herdeiros, logo a fé é vã e a promessa é aniquilada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '15', 'Porque a lei opera a ira. Porque onde não há lei também não há transgressão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '16', 'Porque é pela fé, para que seja segundo a graça, a fim de que a promessa seja firme a toda a posteridade, não somente à que é da fé de Abraão, o qual é pai de todos nós,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '17', '(Como está escrito: Por pai de muitas nações te constituí) perante aquele no qual creu, a saber, Deus, o qual vivifica os mortos, e chama as coisas que não são como se já fossem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '18', 'O qual, em esperança, creu contra a esperança que seria feito pai de muitas nações, conforme o que lhe fora dito: Assim será a tua descendência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '19', 'E não enfraqueceu na fé, nem atentou para o seu próprio corpo já amortecido, pois era já de quase cem anos, nem tampouco para o amortecimento do ventre de Sara.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '20', 'E não duvidou da promessa de Deus por incredulidade, mas foi fortificado na fé, dando glória a Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '21', 'E estando certíssimo de que o que ele tinha prometido também era poderoso para o fazer.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '22', 'Pelo que isso lhe foi também imputado como justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '23', 'Ora não só por causa dele está escrito, que lhe fosse tomado em conta,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '24', 'Mas também por nós, a quem será tomado em conta; os que cremos naquele que dos mortos ressuscitou a Jesus nosso SENHOR;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '4', '25', 'O qual por nossos pecados foi entregue, e ressuscitou para nossa justificação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '1', 'SENDO pois justificados pela fé, temos paz com Deus, por nosso SENHOR Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '2', 'Pelo qual também temos entrada pela fé a esta graça, na qual estamos firmes, e nos gloriamos na esperança da glória de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '3', 'E não somente isto, mas também nos gloriamos nas tribulações; sabendo que a tribulação produz a paciência,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '4', 'E a paciência a experiência, e a experiência a esperança.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '5', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nossos corações pelo Espírito Santo que nos foi dado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '6', 'Porque Cristo, estando nós ainda fracos, morreu a seu tempo pelos ímpios.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '7', 'Porque apenas alguém morrerá por um justo; pois poderá ser que pelo bom alguém ouse morrer.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '8', 'Mas Deus prova o seu amor para connosco, em que Cristo morreu por nós, sendo nós ainda pecadores.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '9', 'Logo muito mais agora, sendo justificados pelo seu sangue, seremos por ele salvos da ira.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '10', 'Porque se nós, sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, estando já reconciliados, seremos salvos pela sua vida.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '11', 'E não somente isto, mas também nos gloriamos em Deus por nosso SENHOR Jesus Cristo, pelo qual agora alcançamos a reconciliação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '12', 'Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado a morte, assim também a morte passou a todos os homens por isso que todos pecaram.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '13', 'Porque até à lei estava o pecado no mundo, mas o pecado não é imputado não havendo lei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '14', 'No entanto a morte reinou desde Adão até Moisés, até sobre aqueles que não pecaram à semelhança da transgressão de Adão, o qual é a figura daquele que havia de vir.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '15', 'Mas não é assim o dom gratuito como a ofensa. Porque, se pela ofensa de um morreram muitos, muito mais a graça de Deus, e o dom pela graça, que é dum só homem, Jesus Cristo, abundou sobre muitos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '16', 'E não foi assim o dom como a ofensa, por um só que pecou. Porque o juízo veio de uma só ofensa, na verdade, para condenação, mas o dom gratuito veio de muitas ofensas para justificação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '17', 'Porque, se pela ofensa de um só, a morte reinou por esse, muito mais os que recebem a abundância da graça, e do dom da justiça, reinarão em vida por um só - Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '18', 'Pois assim como por uma só ofensa veio o juízo sobre todos os homens para condenação, assim também por um só acto de justiça veio a graça sobre todos os homens para justificação de vida.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '19', 'Porque, como pela desobediência de um só homem, muitos foram feitos pecadores, assim pela obediência de um muitos serão feitos justos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '20', 'Veio, porém, a lei para que a ofensa abundasse; mas, onde o pecado abundou, superabundou a graça;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '5', '21', 'Para que, assim como o pecado reinou na morte, também a graça reinasse pela justiça para a vida eterna, por Jesus Cristo nosso SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '1', 'QUE diremos pois? Permaneceremos no pecado, para que a graça abunde?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '2', 'De modo nenhum. Nós, que estamos mortos para o pecado, como viveremos ainda nele?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '3', 'Ou não sabeis que todos quantos fomos baptizados em Jesus Cristo fomos baptizados na sua morte?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '4', 'De sorte que fomos sepultados com ele pelo baptismo na morte; para que como Cristo ressuscitou dos mortos, pela glória do Pai, assim andemos nós também em novidade de vida.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '5', 'Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '6', 'Sabemos isto, que o nosso homem velho foi com ele crucificado, para que o corpo do pecado seja desfeito, para que não sirvamos mais ao pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '7', 'Porque aquele que está morto está justificado do pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '8', 'Ora, se já morremos com Cristo, cremos que também com ele viveremos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '9', 'Sabemos que, havendo Cristo ressuscitado dos mortos, já não morre; a morte não mais terá domínio sobre ele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '10', 'Pois, quanto a ter morrido, de uma vez morreu para o pecado, mas, quanto a viver, vive para Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '11', 'Assim também vós considerai-vos como mortos para o pecado, mas vivos para Deus em Cristo Jesus nosso SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '12', 'Não reine portanto o pecado em vosso corpo mortal, para lhe obedecerdes em suas concupiscências;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '13', 'Nem tampouco, apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos de entre mortos, e os vossos membros a Deus, como instrumentos de justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '14', 'Porque o pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '15', 'Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '16', 'Não sabeis vós que a quem vos apresentardes por servos para lhe obedecer, sois servos daquele a quem obedeceis, ou do pecado para a morte, ou da obediência para a justiça?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '17', 'Mas graças a Deus que, tendo sido servos do pecado, obedecestes de coração à forma de doutrina a que fostes entregues.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '18', 'E, libertados do pecado, fostes feitos servos da justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '19', 'Falo como homem, pela fraqueza da vossa carne: pois que, assim como apresentastes os vossos membros para servirem à imundície, e à maldade para maldade, assim apresentai agora os vossos membros para servirem à justiça para santificação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '20', 'Porque, quando éreis servos do pecado, estáveis livres da justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '21', 'E que fruto tínheis então das coisas de que agora vos envergonhais? Porque o fim delas é a morte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '22', 'Mas agora, libertados do pecado, e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '6', '23', 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus nosso SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '1', 'NÃO sabeis vós, irmãos (pois que falo aos que sabem a lei), que a lei tem domínio sobre o homem por todo o tempo que vive?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '2', 'Porque a mulher que está sujeita ao marido, enquanto ele viver, está-lhe ligada pela lei; mas, morto o marido, está livre da lei do marido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '3', 'De sorte que, vivendo o marido, será chamada adúltera, se for doutro marido; mas, morto o marido, livre está da lei, e assim não será adúltera, se for doutro marido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '4', 'Assim, meus irmãos, também vós estais mortos para a lei pelo corpo de Cristo, para que sejais doutro, daquele que ressuscitou de entre os mortos, a fim de que dêmos fruto para Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '5', 'Porque, quando estávamos na carne, as paixões dos pecados, que, são pela lei, obravam em nossos membros para darem fruto, para a morte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '6', 'Mas agora estamos livres da lei, pois morremos para aquilo em que estávamos retidos; para que sirvamos em novidade de espírito, e não na velhice da letra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '7', 'Que diremos pois? É a lei pecado? De modo nenhum. Mas eu não conheci o pecado senão pela lei; porque eu não conheceria a concupiscência, se a lei não dissesse: Não cobiçarás.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '8', 'Mas o pecado, tomando ocasião pelo mandamento, obrou em mim toda a concupiscência: porquanto sem a lei estava morto o pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '9', 'E eu, nalgum tempo, vivia sem lei, mas, vindo o mandamento, reviveu o pecado, e eu morri;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '10', 'E o mandamento que era para vida achei eu que me era para morte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '11', 'Porque o pecado, tomando ocasião pelo mandamento, me enganou, e por ele me matou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '12', 'E assim a lei é santa, e o mandamento santo, justo e bom.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '13', 'Logo tornou-se-me o bom em morte? De modo nenhum; mas o pecado, para que se mostrasse pecado; operou em mim a morte pelo bem; a fim de que pelo mandamento o pecado se fizesse excessivamente maligno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '14', 'Porque bem sabemos que a lei é espiritual: mas eu sou carnal, vendido sob o pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '15', 'Porque o que faço não o aprovo; pois o que quero isso não faço, mas o que aborreço isso faço.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '16', 'E, se faço o que não quero, consinto com a lei, que é boa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '17', 'De maneira que agora já não sou eu que faço isto, mas o pecado que habita em mim.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '18', 'Porque eu sei que em mim, isto é, na minha carne, não habita bem algum: e com efeito o querer está em mim, mas não consigo realizar o bem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '19', 'Porque não faço o bem que quero, mas o mal que não quero esse faço.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '20', 'Ora, se eu faço o que não quero, já o não faço eu, mas o pecado que habita em mim.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '21', 'Acho então esta lei em mim: que, quando quero fazer o bem, o mal está comigo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '22', 'Porque, segundo o homem interior, tenho prazer na lei de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '23', 'Mas vejo nos meus membros outra lei, que batalha contra a lei do meu entendimento, e me prende debaixo da lei do pecado que está nos meus membros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '24', 'Miserável homem que eu sou! Quem me livrará do corpo desta morte?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '7', '25', 'Dou graças a Deus por Jesus Cristo nosso SENHOR. Assim que eu mesmo com o entendimento sirvo à lei de Deus, mas com a carne à lei do pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '1', 'PORTANTO agora nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '2', 'Porque a lei do espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '3', 'Porquanto o que era impossível à lei, visto como estava enferma pela carne, Deus, enviando o seu Filho em semelhança da carne do pecado, pelo pecado condenou o pecado na carne;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '4', 'Para que a justiça da lei se cumprisse em nós, que não andamos segundo a carne, mas segundo o espírito.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '5', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o espírito para as coisas do espírito.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '6', 'Porque a inclinação da carne é morte; mas a inclinação do espírito é vida e paz.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '7', 'Porquanto a inclinação da carne é inimizade contra Deus, pois não é sujeita à lei de Deus, nem, em verdade, o pode ser.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '8', 'Portanto os que estão na carne não podem agradar a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '9', 'Vós, porém, não estais na carne, mas no Espírito, se é que o Espírito de Deus habita em vós. Mas; se alguém não tem o Espírito de Cristo, esse tal não é dele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '10', 'E, se Cristo está em vós, o corpo, na verdade, está morto por causa do pecado, mas o espírito vive por causa da justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '11', 'E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará os vossos corpos mortais, pelo seu Espírito que em vós habita.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '12', 'De maneira que, irmãos, somos devedores, não à carne para viver segundo a carne.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '13', 'Porque, se viverdes segundo a carne, morrereis; mas, se pelo espírito mortificardes as obras do corpo vivereis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '14', 'Porque todos os que são guiados pelo Espírito de Deus esses são filhos de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '15', 'Porque não recebestes o espírito de escravidão, para outra vez estardes em temor, mas recebestes o espírito de adopção de filhos, pelo qual clamamos: Aba, Pai.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '16', 'O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '17', 'E, se nós somos filhos, somos logo herdeiros também, herdeiros de Deus e co-herdeiros de Cristo: se é certo que com ele padecemos, para que também com ele sejamos glorificados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '18', 'Porque para mim tenho por certo que as aflições deste tempo presente não são para comparar com a glória que em nós há-de ser revelada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '19', 'Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '20', 'Porque a criação ficou sujeita à vaidade, não por sua vontade, mas por causa do que a sujeitou,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '21', 'Na esperança de que também a mesma criatura será libertada da servidão da corrupção, para a liberdade da glória dos filhos de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '22', 'Porque sabemos que toda a criatura geme e está juntamente com dores de parto até agora.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '23', 'E não só ela, mas nós mesmos, que temos as primícias do Espírito, também gememos em nós mesmos, esperando a adopção, a saber, a redenção do nosso corpo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '24', 'Porque em esperança somos salvos. Ora a esperança que se vê não é esperança; porque o que alguém vê como o esperará?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '25', 'Mas, se esperamos o que não vemos, com paciência o esperamos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '26', 'E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '27', 'E aquele que examina os corações sabe qual é a intenção do Espírito; e é ele que segundo Deus intercede pelos santos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '28', 'E sabemos que todas as coisas contribuem juntamente para o bem daqueles que são chamados por seu decreto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '29', 'Porque os que dantes conheceu também os predestinou para serem conformes à imagem de seu Filho; a fim de que ele seja o primogénito entre muitos irmãos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '30', 'E aos que predestinou a estes também chamou; e aos que chamou a estes também justificou; e aos que justificou a estes também glorificou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '31', 'Que diremos pois a estas coisas? Se Deus é por nós, quem será contra nós?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '32', 'Aquele que nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós, como nos não dará também com ele todas as coisas?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '33', 'Quem intentará acusação contra os escolhidos de Deus? É Deus quem os justifica.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '34', 'Quem os condenará? Pois é Cristo quem morreu, ou antes quem ressuscitou de entre os mortos, o qual está à direita de Deus, e também intercede por nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '35', 'Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '36', 'Como está escrito: Por amor de ti somos entregues à morte todo o dia: fomos reputados como ovelhas para o matadouro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '37', 'Mas em todas estas coisas somos mais do que vencedores, por aquele que nos amou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '38', 'Porque estou certo de que, nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '8', '39', 'Nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '1', 'EM Cristo digo a verdade, não minto (dando-me testemunho a minha consciência no Espírito Santo);');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '2', 'Que tenho grande tristeza e contínua dor no meu coração.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '3', 'Porque eu mesmo poderia desejar ser separado de Cristo, por amor de meus irmãos, que são meus parentes segundo a carne;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '4', 'Que são israelitas, dos quais é a adopção de filhos, e a glória, e os concertos, e a lei, e o culto, e as promessas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '5', 'Dos quais são os pais, e dos quais é Cristo segundo a carne, o qual é sobre todos; Deus bendito eternamente: Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '6', 'Não que a palavra de Deus haja faltado, porque nem todos os que são de Israel são israelitas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '7', 'Nem por serem descendência de Abraão são todos filhos; mas: Em Isaque será chamada a tua descendência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '8', 'Isto é: não são os filhos da carne que são filhos de Deus, mas os filhos da promessa são contados como descendência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '9', 'Porque a palavra da promessa é esta: Por este tempo virei, e Sara terá um filho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '10', 'E não somente esta, mas também Rebeca, quando concebeu de um, de Isaque, nosso pai;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '11', 'Porque, não tendo eles ainda nascido, nem tendo feito bem ou mal (para que o propósito de Deus, segundo a eleição, ficasse firme, não por causa das obras, mas por aquele que chama),');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '12', 'Foi-lhe dito a ela: O maior servirá o menor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '13', 'Como está escrito: Amei Jacob e aborreci a Esaú.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '14', 'Que diremos pois? Que há injustiça da parte de Deus? De maneira nenhuma.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '15', 'Pois dizia Moisés: Compadecer-me-ei de quem me compadecer, e terei misericórdia de quem eu tiver misericórdia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '16', 'Assim, pois, isto não depende do que quer, nem de que corre, mas de Deus, que se compadece.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '17', 'Porque diz a Escritura a Faraó: Para isto mesmo te levantei: Para em ti mostrar o meu poder, e para que o meu nome seja anunciado em toda a terra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '18', 'Logo pois compadece-se de quem quer, e endurece a quem quer.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '19', 'Dir-me-ás então: Porque se queixa ele ainda? Porquanto, quem resiste à sua vontade?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '20', 'Mas, ó homem, quem és tu, que a Deus replicas? Porventura a coisa formada dirá ao que a formou: Porque me, fizeste assim?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '21', 'Não tem o oleiro poder sobre o barro, para da mesma massa fazer um vaso para a honra e outro para desonra?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '22', 'E que direis se Deus querendo mostrar a sua ira, e dar a conhecer o seu poder, suportou com muita paciência os vasos da ira, preparados para a perdição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '23', 'Para que também desse a conhecer as riquezas da sua glória nos vasos de misericórdia, que para glória já dantes preparou,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '24', 'Os quais somos nós, a quem também chamou, não só dentre os judeus, mas também dentre os gentios?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '25', 'Como também diz em Oseias: Chamarei meu povo ao que não era meu povo; e amada à que não era amada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '26', 'E sucederá que no lugar em que lhes foi dito: Vós não sois meu povo; aí serão chamados filhos do Deus vivo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '27', 'Também Isaías clamava acerca de Israel: Ainda que o número dos filhos de Israel seja como a areia do mar, o remanescente é que será salvo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '28', 'Porque o SENHOR executará a sua palavra sobre a terra, completando-a e abreviando-a.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '29', 'E como antes disse Isaías: Se o SENHOR dos Exércitos nos não deixara descendência, teríamos sido feitos como Sodoma e seríamos semelhantes a Gomorra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '30', 'Que diremos pois? Que os gentios, que não buscavam a justiça, alcançaram a justiça? Sim, mas a justiça que é pela fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '31', 'Mas Israel, que buscava a lei da justiça, não chegou à lei da justiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '32', 'Porquê? Porque não foi pela fé, mas como que pelas obras da lei; tropeçaram na pedra de tropeço;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '9', '33', 'Como está escrito: Eis que eu ponho em Sião uma pedra de tropeço, e uma rocha de escândalo; e todo aquele que crer nela não será confundido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '1', 'IRMÃOS, o bom desejo do meu coração e a oração a Deus por Israel é para sua salvação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '2', 'Porque lhes dou testemunho de que têm zelo de Deus, mas não com entendimento.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '3', 'Porquanto, não conhecendo a justiça de Deus, e procurando estabelecer a sua própria justiça, não se sujeitaram à justiça de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '4', 'Porque o fim da lei é Cristo para justiça de todo aquele que crê.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '5', 'Ora Moisés descreve a justiça que é pela lei, dizendo: O homem que fizer estas coisas viverá por elas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '6', 'Mas a justiça que é pela fé diz assim: Não digas em teu coração: Quem subirá ao céu? (isto é, a trazer do alto a Cristo).');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '7', 'Ou: Quem descerá ao abismo? (isto é, a tornar a trazer de entre os mortos a Cristo).');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '8', 'Mas que diz? A palavra está junto de ti, na tua boca e no teu coração; esta é a palavra da fé, que pregamos,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '9', 'A saber: Se com a tua boca confessares ao SENHOR Jesus, e, em teu coração creres que Deus o ressuscitou dos mortos, serás salvo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '10', 'Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '11', 'Porque a Escritura diz: Todo aquele que nele crer não será confundido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '12', 'Porquanto não há diferença entre judeu e grego; porque um mesmo é o SENHOR de todos os que o invocam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '13', 'Porque todo aquele que invocar o nome do SENHOR será salvo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '14', 'Como pois invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram? E como ouvirão, se não há quem pregue?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '15', 'E como pregarão, se não forem enviados? Como está escrito: Quão formosos os pés dos que anunciam a paz, dos que anunciam coisas boas!');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '16', 'Mas nem todos obedecem ao evangelho; pois Isaías diz: Senhor, quem creu na nossa pregação?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '17', 'De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '18', 'Mas digo: Porventura não ouviram? Sim, por certo, pois por toda a terra saiu a voz deles, e as suas palavras até aos confins do mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '19', 'Mas digo: Porventura Israel não o soube? Primeiramente diz Moisés: Eu vos meterei em ciúmes com aqueles que não são povo, com gente insensata vos provocarei à ira.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '20', 'E Isaías ousadamente diz: Fui achado pelos que me não buscavam, fui manifestado aos que por mim não perguntavam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '10', '21', 'Mas contra Israel diz. Todo o dia estendi as minhas mãos a um povo rebelde e contradizente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '1', 'DIGO pois: porventura rejeitou Deus o seu povo? De modo nenhum, porque também eu sou israelita, da descendência de Abraão, da tribo de Benjamim.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '2', 'Deus não rejeitou o seu povo, que antes conheceu. Ou não sabeis o que a Escritura diz de Elias, como fala a Deus contra Israel, dizendo:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '3', 'Senhor, mataram os teus profetas, e derribaram os teus altares; e só eu fiquei, e buscam a minha alma?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '4', 'Mas que lhe diz a resposta divina? Reservei para mim sete mil varões, que não dobraram os joelhos diante de Baal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '5', 'Assim pois também agora neste tempo ficou um resto, segundo a eleição da graça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '6', 'Mas se é por graça, já não é pelas obras, de outra maneira, a graça já não é graça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '7', 'Pois quê? O que Israel buscava não o alcançou; mas os eleitos o alcançaram, e os outros foram endurecidos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '8', 'Como está escrito: Deus lhes deu espirito de profundo sono, olhos para não verem , e ouvidos para não ouvirem, até ao dia de hoje.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '9', 'E David diz: Torne-se-lhes a sua mesa em laço, e em armadilha, e em tropeço, por sua retribuição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '10', 'Escureçam-se-lhes os olhos para não verem, e encurvem-se-lhes continuamente as costas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '11', 'Digo pois: Porventura tropeçaram para que caíssem? De modo nenhum, mas pela sua queda veio a salvação aos gentios, para os incitar à emulação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '12', 'E se a sua queda é a riqueza do mundo, e a sua diminuição a riqueza dos gentios, quanto mais a sua plenitude!');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '13', 'Porque convosco falo, gentios, que, enquanto for apóstolo dos gentios, glorificarei o meu ministério;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '14', 'Para ver se de alguma maneira posso incitar à emulação os da minha carne e salvar alguns deles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '15', 'Porque, se a sua rejeição é a reconciliação do mundo, qual será a sua admissão, senão a vida entre os mortos?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '16', 'E, se as primícias são santas, também a massa o é; se a raiz é santa, também os ramos o são.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '17', 'E se alguns dos ramos foram quebrados, e tu, sendo zambujeiro, foste enxertado em lugar deles, e feito participante da raiz e da seiva da oliveira,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '18', 'Não te glorieis contra os ramos; e, se contra eles te gloriares, não és tu que sustentas a raiz, mas a raiz a ti.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '19', 'Dirás pois: Os ramos foram quebrados, para que eu fosse enxertado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '20', 'Está bem: pela sua incredulidade foram quebrados, e tu estás em pé pela fé. Então não te ensoberbeças, mas teme.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '21', 'Porque, se Deus não poupou os ramos naturais, teme que te não poupe a ti também.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '22', 'Considera pois a bondade e a severidade de Deus: para com os que caíram, severidade; mas para contigo, a benignidade de Deus, se permaneceres na sua benignidade; de outra maneira também tu serás cortado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '23', 'E também eles, se não permanecerem na incredulidade, serão enxertados; porque poderoso é Deus para os tornar a enxertar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '24', 'Porque, se tu foste cortado do natural zambujeiro, e, contra a natureza enxertado na boa oliveira, quanto mais esses, que são naturais, serão enxertados na sua própria oliveira!');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '25', 'Porque não quero, irmãos, que ignoreis este segredo (para que não presumais de vós mesmos): que o endurecimento veio em parte sobre Israel, até que a plenitude dos gentios haja entrado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '26', 'E assim todo o Israel será salvo, como está escrito: de Sião virá o Libertador, e desviará de Jacob as impiedades.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '27', 'E este será o meu concerto com eles, quando eu tirar os seus pecados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '28', 'Assim que, quanto ao evangelho, são inimigos por causa de vós; mas, quanto à eleição, amados por causa dos pais.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '29', 'Porque os dons e a vocação de Deus são sem arrependimento.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '30', 'Porque assim como vós também antigamente fostes desobedientes a Deus, mas agora alcançastes misericórdia pela desobediência deles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '31', 'Assim também estes agora foram desobedientes, para também alcançarem misericórdia pela misericórdia a vós demonstrada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '32', 'Porque Deus encerrou a todos debaixo da desobediência, para com todos usar de misericórdia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '33', 'Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis os seus caminhos!');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '34', 'Porque quem compreendeu o intento do SENHOR? Ou quem foi o seu conselheiro?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '35', 'Ou quem lhe deu primeiro a ele, para que lhe seja recompensado?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '11', '36', 'Porque dele e por ele, e para ele, são todas as coisas; glória pois a ele eternamente. Amém.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '1', 'ROGO-VOS pois irmãos, pela compaixão de Deus, que apresenteis os vossos corpos em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '2', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável, e perfeita vontade de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '3', 'Porque pela graça, que me é dada, digo a cada um de entre vós que não saiba mais do que convém saber, mas que saiba com temperança, conforme a medida da fé que Deus repartiu a cada um.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '4', 'Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '5', 'Assim nós, que somos muitos, somos um só corpo em Cristo; mas individualmente somos membros uns dos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '6', 'De modo que, tendo diferentes dons, segundo a graça que nos é dada, se é profecia, seja ela segundo a medida da fé;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '7', 'Se é ministério, seja em ministrar; se é ensinar haja dedicação ao ensino,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '8', 'Ou o que exorta, use esse dom em exortar; o que reparte, faça-o com liberalidade; o que preside, com cuidado; o que exercita misericórdia, com alegria.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '9', 'O amor seja não fingido. Aborrecei o mal e apegai-vos ao bem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '10', 'Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '11', 'Não sejais vagarosos no cuidado: sede fervorosos no espírito, servindo ao SENHOR;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '12', 'Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '13', 'Comunicai com os santos nas suas necessidades, segui a hospitalidade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '14', 'Abençoai aos que vos perseguem, abençoai, e não amaldiçoeis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '15', 'Alegrai-vos com os que se alegram; e chorai com os que choram;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '16', 'Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '17', 'A ninguém torneis mal por mal; procurai as coisas honestas, perante todos os homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '18', 'Se for possível, quanto estiver em vós, tende paz com todos os homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '19', 'Não vos vingueis a vós mesmos, amados, mas dai lugar à ira, porque está escrito: Minha é a vingança; eu recompensarei, diz o SENHOR,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '20', 'Portanto, se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isto, amontoarás brasas de fogo sobre a sua cabeça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '12', '21', 'Não te deixes vencer do mal, mas vence o mal com o bem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '1', 'TODA a alma esteja sujeita às potestades superiores; porque não há potestade que não venha de Deus; e as potestades que há foram ordenadas por Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '2', 'Por isso quem resiste à potestade resiste à ordenação de Deus; e os que resistem trarão sobre si mesmos a condenação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '3', 'Porque os magistrados não são terror para as boas obras, mas para as más. Queres tu, pois, não temer a potestade? Faz o bem, e terás louvor dela.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '4', 'Porque ela é ministro de Deus para teu bem. Mas, se fizeres o mal, teme, pois não traz debalde a espada; porque é ministro de Deus, e vingador para castigar o que faz o mal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '5', 'Portanto é necessário que lhe estejais sujeitos, não somente pelo castigo, mas também pela consciência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '6', 'Por esta razão também pagais tributos: porque são ministros de Deus, atendendo sempre a isto mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '7', 'Portanto dai a cada um o que deveis: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '8', 'A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros: porque quem ama aos outros cumpriu a lei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '9', 'Com efeito: Não adulterarás, não matarás, não furtarás, não darás falso testemunho, não cobiçarás; e se há algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '10', 'O amor não faz mal ao próximo. De sorte que o cumprimento da lei é o amor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '11', 'E isto digo, conhecendo o tempo, que é já hora de despertarmos do sono; porque a nossa salvação está agora mais perto de nós do que quando aceitámos a fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '12', 'A noite é passada, e o dia é chegado. Rejeitemos pois as obras das trevas, e vistamo-nos das armas da luz.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '13', 'Andemos honestamente, como de dia: não em glutonarias, nem em bebedeiras, nem em desonestidade, nem em dissoluções, nem em contendas e inveja.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '13', '14', 'Mas revesti-vos do SENHOR Jesus Cristo, e não tenhais cuidado da carne em suas concupiscências.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '1', 'ORA, quanto ao que está enfermo na fé, recebei-o, não em contendas sobre dúvidas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '2', 'Porque um crê que de tudo se pode comer, e outro, que é fraco, come legumes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '3', 'O que come não despreze o que não come; e o que não come não julgue o que come; porque Deus o recebeu por seu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '4', 'Quem és tu, que julgas o servo alheio? Para seu próprio SENHOR ele está em pé ou cai; mas estará firme; porque poderoso é Deus para o firmar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '5', 'Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '6', 'Aquele que faz caso do dia, para o SENHOR o faz. O que come, para o SENHOR come, porque dá graças a Deus; e o que não come, para o SENHOR não come, e dá graças a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '7', 'Porque nenhum de nós vive para si, e nenhum morre para si.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '8', 'Porque, se vivemos, para o SENHOR vivemos: se morremos, para o SENHOR morremos. De sorte que, ou vivamos ou morramos, somos do SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '9', 'Foi para isto que morreu Cristo, e tornou a viver; para ser Senhor, tanto dos mortos, como dos vivos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '10', 'Mas tu, porque julgas teu irmão? Ou tu, também, porque desprezas teu irmão? Pois todos havemos de comparecer ante o tribunal de Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '11', 'Porque está escrito: Pela minha vida, diz o SENHOR: que todo o joelho se dobrará diante de mim, e toda a língua confessará a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '12', 'De maneira que cada um de nós dará conta de si mesmo a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '13', 'Assim que não nos julguemos mais uns aos outros; antes seja o vosso propósito não pôr tropeço ou escândalo ao irmão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '14', 'Eu sei, e estou certo no SENHOR Jesus, que nenhuma coisa é de si mesmo imunda a não ser para aquele que a tem por imunda; para esse é imunda.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '15', 'Mas, se por causa da comida se contrista teu irmão, já não andas conforme o amor. Não destruas por causa da tua comida aquele por quem Cristo morreu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '16', 'Não seja pois blasfemado o vosso bem;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '17', 'Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '18', 'Porque quem nisto serve a Cristo agradável é a Deus e aceito aos homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '19', 'Sigamos pois as coisas que servem para a paz e para a edificação de uns para com os outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '20', 'Não destruas por causa da comida a obra de Deus. É verdade que tudo é limpo, mas mal vai para o homem que come com escândalo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '21', 'Bom é não comer carne, nem beber vinho, nem fazer outras coisas em que teu irmão tropece, ou se escandalize, ou se enfraqueça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '22', 'Tens tu fé? Tem-na em ti mesmo diante de Deus. Bem-aventurado aquele que não se condena a si mesmo naquilo que aprova.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '14', '23', 'Mas aquele que tem dúvidas, se come está condenado, porque não come por fé; e tudo o que não é de fé é pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '1', 'MAS nós, que somos fortes, devemos suportar as fraquezas dos fracos, e não agradar a nós mesmos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '2', 'Portanto cada um de nós agrade ao seu próximo no que é bom para edificação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '3', 'Porque também Cristo não agradou a si mesmo, mas, como está escrito: sobre mim caíram as injúrias dos que te injuriavam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '4', 'Porque tudo que dantes foi escrito, para nosso ensino foi escrito, para que pela paciência e consolação das Escrituras tenhamos esperança.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '5', 'Ora o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '6', 'Para que concordes, a uma boca, glorifiqueis ao Deus e Pai de nosso SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '7', 'Portanto recebei-vos uns aos outros, como também Cristo nos recebeu para glória de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '8', 'Digo pois que Jesus Cristo foi ministro da circuncisão, por causa da verdade de Deus, para que confirmasse as promessas feitas aos pais;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '9', 'E para que os gentios glorifiquem a Deus pela sua misericórdia, como está escrito: Portanto eu te louvarei entre os gentios, e cantarei ao teu nome.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '10', 'E outra vez diz: Alegrai-vos, gentios, com o seu povo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '11', 'E outra vez: Louvai ao SENHOR, todos os gentios, e celebrai-o, todos os povos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '12', 'E outra vez diz Isaías: Uma raiz em Jessé haverá, e naquele que se levantar para reger os gentios, os gentios esperarão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '13', 'Ora o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '14', 'Eu próprio, meus irmãos, certo estou, a respeito de vós, que vós mesmos estais cheios de bondade, cheios de todo o conhecimento, podendo admoestar-vos uns aos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '15', 'Mas, irmãos, em parte vos escrevi mais ousadamente, como para vos trazer outra vez isto à memória, pela graça que por Deus me foi dada;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '16', 'Que seja ministro de Jesus Cristo entre os gentios, ministrando o evangelho de Deus, para que seja agradável a oferta dos gentios, santificada pelo Espírito Santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '17', 'De sorte que tenho glória em Jesus Cristo nas coisas que pertencem a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '18', 'Porque não ousaria dizer coisa alguma, que Cristo por mim não tenha feito, a obediência dos gentios, por palavra e por obras;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '19', 'Pelo poder dos sinais e prodígios, na virtude do Espírito de Deus: de maneira que desde Jerusalém, e arredores, até ao Ilírico, tenho pregado o evangelho de Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '20', 'E desta maneira me esforcei por anunciar o evangelho, não onde Cristo houvera sido nomeado, para não edificar sobre fundamento alheio;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '21', 'Antes, como está escrito: Aqueles a quem não foi anunciado, o verão, e os que não ouviram o entenderão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '22', 'Pelo que também muitas vezes tenho sido impedido de ir ter convosco.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '23', 'Mas agora, que não tenho mais demora nestes sítios, e tendo já há muitos anos grande desejo de ir ter convosco.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '24', 'Quando partir para Espanha irei ter convosco; pois espero que de passagem vos verei, e que para lá seja encaminhado por vós, depois de ter gozado um pouco da vossa companhia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '25', 'Mas agora vou a Jerusalém para ministrar aos santos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '26', 'Porque pareceu bem à Macedónia e à Acaia fazerem uma colecta para os pobres de entre os santos que estão em Jerusalém.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '27', 'Isto lhes pareceu bem, como devedores que são para com eles. Porque, se os gentios foram participantes dos seus bens espirituais, devem também ministrar-lhes os temporais.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '28', 'Assim que, concluído isto, e havendo-lhes consignado este fruto, de lá, passando por vós, irei à Espanha.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '29', 'E bem sei que, indo ter convosco, chegarei com a plenitude da bênção do evangelho de Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '30', 'E rogo-vos irmãos, por nosso SENHOR Jesus Cristo e, pelo amor do Espírito, que combatais comigo nas vossas orações por mim a Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '31', 'Para que seja livre dos rebeldes que estão na Judeia, e que esta minha administração, que em Jerusalém faço, seja bem aceita pelos santos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '32', 'A fim de que, pela vontade de Deus, chegue a vós com alegria, e possa recrear-me convosco.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '15', '33', 'E o Deus de paz seja com todos vós. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '1', 'RECOMENDO-VOS pois Febe, nossa irmã, a qual serve na igreja que está em Cencreia,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '2', 'Para que a recebais no SENHOR, como convém aos santos, e a ajudeis em qualquer coisa que de vós necessitar; porque tem hospedado a muitos, como também a mim mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '3', 'Saudai a Priscila e a Áquila, meus cooperadores em Cristo Jesus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '4', 'Os quais pela minha vida expuseram as suas cabeças; o que não só eu lhes agradeço, mas também todas as igrejas dos gentios.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '5', 'Saudai também a igreja que está em sua casa. Saudai a Epéneto, meu amado, que é as primícias da Ásia em Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '6', 'Saudai a Maria que trabalhou muito por nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '7', 'Saudai a Andrónico e a Júnia, meus parentes e meus companheiros na prisão, os quais se distinguiram entre os apóstolos e que foram antes de mim em Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '8', 'Saudai a Amplias, meu amado no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '9', 'Saudai a Urbano, nosso cooperador em Cristo, e a Estáquis, meu amado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '10', 'Saudai a Apeles aprovado em Cristo. Saudai aos da família de Aristóbulo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '11', 'Saudai a Herodião, meu parente. Saudai aos da família de Narciso, os que estão no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '12', 'Saudai a Trifena e a Trifosa, as quais trabalham no SENHOR. Saudai a amada Pérside, a qual muito trabalhou no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '13', 'Saudai a Rufo, eleito no SENHOR, e a sua mãe e minha.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '14', 'Saudai a Asíncrito, a Flegonte, a Hermas, a Pátrobas, a Hermes, e aos irmãos que estão com eles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '15', 'Saudai a Filólogo e a Júlia, a Nereu e a sua irmã, e a Olímpia; e a todos os santos que com eles estão. l');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '16', 'Saudai-vos uns aos outros com santo ósculo. As igrejas de Cristo vos saúdam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '17', 'E rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '18', 'Porque os tais não servem a nosso SENHOR Jesus Cristo, mas ao seu ventre: e com suaves palavras e lisonjas enganam os corações dos símplices.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '19', 'Quanto à vossa obediência é ela conhecida de todos. Comprazo-me pois em vós; e quero que sejais sábios no bem, mas símplices no mal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '20', 'E o Deus de paz esmagará em breve Satanás debaixo dos vossos pés. A graça de Nosso SENHOR Jesus Cristo seja convosco. Amém.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '21', 'Saúdam-vos Timóteo, meu cooperador, e Lúcio, e Jason, e Sosípatro, meus parentes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '22', 'Eu, Tércio, que esta carta escrevi, vos saúdo no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '23', 'Saúda-vos Gaio, meu hospedeiro, e de toda a igreja. Saúda-vos Erasto, procurador da cidade, e também o irmão Quarto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '24', 'A graça de nosso SENHOR Jesus Cristo seja com todos vós. Amém.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '25', 'Ora, aquele que é poderoso para vos confirmar segundo o meu evangelho e a pregação de Jesus Cristo, conforme a revelação do mistério que desde tempos eternos esteve oculto,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '26', 'Mas que se manifestou agora, e se notificou pelas Escrituras dos profetas, segundo o mandamento do Deus eterno, a todas as nações para obediência da fé;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('45', '16', '27', 'Ao único Deus, sábio, seja dada glória por Jesus Cristo para todo o sempre. Amém.');