INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '1', '¶ PAULO, apóstolo de Jesus Cristo, pela vontade de Deus, aos santos que estão em Éfeso, e fiéis em Cristo Jesus:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '2', 'A vós graça, e paz da parte de Deus nosso Pai e da do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '3', 'Bendito o Deus e Pai de nosso SENHOR Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '4', 'Como também nos elegeu nele antes da fundação do mundo, para que fôssemos santos e irrepreensíveis diante dele em caridade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '5', 'E nos predestinou para filhos de adopção por Jesus Cristo, para si mesmo, segundo o benefício da sua vontade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '6', 'Para louvor e glória da sua graça, pela qual nos fez agradáveis a si no Amado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '7', 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '8', 'Que Ele fez abundar para connosco em toda a sabedoria e prudência;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '9', 'Descobrindo-nos o mistério da sua vontade, segundo o seu beneplácito, que propusera em si mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '10', 'De tornar a congregar em Cristo todas as coisas, na dispensação da plenitude dos tempos, tanto as que estão nos céus como as que estão na terra;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '11', 'Nele, digo, em quem também fomos feitos herança, havendo sido predestinados, conforme o propósito daquele que faz todas as coisas, segundo o conselho da sua vontade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '12', 'Com o fim de sermos para louvor da sua glória, nós, os que primeiro esperámos em Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '13', 'Em quem também vós estais, depois que ouvistes a palavra da verdade, o evangelho da vossa salvação; e, tendo nele também crido, fostes selados com o Espírito Santo da promessa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '14', 'O qual é o penhor da nossa herança, para redenção da possessão de Deus, para louvor da sua glória.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '15', 'Pelo que, ouvindo eu também a fé que entre vós há no SENHOR Jesus, e a vossa caridade para com todos os santos,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '16', 'Não cesso de dar graças a Deus por vós, lembrando-me de vós nas minhas orações;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '17', 'Para que o Deus de nosso SENHOR Jesus Cristo, o Pai da glória, vos dê em seu conhecimento o espírito de sabedoria e de revelação;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '18', 'Tendo iluminado os olhos do vosso entendimento, para que saibais qual seja a esperança da sua vocação, e quais as riquezas da glória da sua herança nos santos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '19', 'E qual a sobre excelente grandeza do seu poder sobre nós, os que cremos, segundo a operação da força do seu poder,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '20', 'Que manifestou em Cristo, ressuscitando-o dos mortos, e pondo-o à sua direita nos céus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '21', 'Acima de todo o principado, e poder, e potestade, e domínio, e de todo o nome que se nomeia, não só neste século, mas também no vindouro;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '22', 'E sujeitou todas as coisas a seus pés, e sobre todas as coisas o constituiu como cabeça da igreja,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '1', '23', 'Que é o seu corpo, a plenitude daquele que cumpre tudo em todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '1', 'E VOS vivificou estando vós mortos em ofensas e pecados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '2', 'Em que noutro tempo andastes segundo o curso deste mundo, segundo o príncipe das potestades do ar, do espírito que agora opera nos filhos da desobediência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '3', 'Entre os quais todos nós também antes andávamos nos desejos da nossa carne, fazendo a vontade da carne e dos pensamentos; e éramos por natureza filhos da ira, como os outros também.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '4', 'Mas Deus, que é riquíssimo em misericórdia, pelo seu muito amor com que nos amou,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '5', 'Estando nós ainda mortos em nossas ofensas, nos vivificou juntamente com Cristo (pela graça sois salvos).');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '6', 'E nos ressuscitou juntamente com ele, e nos fez assentar nos lugares celestiais, em Cristo Jesus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '7', 'Para prostrar nos séculos vindouros as abundantes riquezas da sua graça, pela sua benignidade para connosco em Cristo Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '8', 'Porque pela graça sois salvos, por meio da fé; e isto não vem de vós; é dom de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '9', 'Não vem das obras, para que ninguém se glorie.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '10', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '11', 'Portanto, lembrai-vos de que vós noutro tempo éreis gentios na carne e chamados incircuncisão pelos que na carne se chamam circuncisão feita pela mão dos homens;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '12', 'Que naquele tempo estáveis sem Cristo, separados da comunidade de Israel, e estranhos aos concertos da promessa, não tendo esperança, e sem Deus no mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '13', 'Mas agora em Cristo Jesus, vós, que antes estáveis longe, já, pelo sangue de Cristo chegastes perto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '14', 'Porque ele é a nossa paz, o qual de ambos os povos fez um; e, derribando a parede de separação que estava no meio,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '15', 'Na sua carne desfez a inimizade, isto é, a lei dos mandamentos, que consistia em ordenanças, para dos dois criar em si mesmo um novo homem, fazendo a paz,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '16', 'E pela cruz reconciliar ambos com Deus em um corpo, matando com ela as inimizades.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '17', 'E, vindo, ele evangelizou a paz, a vós que estáveis longe, e aos que estavam perto;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '18', 'Porque por ele ambos temos acesso ao Pai em um mesmo Espírito,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '19', 'Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos santos, e da família de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '20', 'Edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '21', 'No qual todo o edifício, bem ajustado, cresce para templo santo no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '2', '22', 'No qual também vós juntamente sois edificados para morada de Deus em Espírito.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '1', 'POR esta causa eu, Paulo, sou o prisioneiro de Jesus Cristo por vós, os gentios;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '2', 'Se é que tendes ouvido a dispensação da graça de Deus, que para convosco me foi dada;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '3', 'Como me foi este mistério manifestado pela revelação como acima em pouco vos escrevi;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '4', 'Pelo que, quando lerdes, podeis perceber a minha compreensão do mistério de Cristo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '5', 'O qual noutros séculos não foi manifestado aos filhos dos homens, como agora tem sido revelado pelo Espírito aos seus santos apóstolos e profetas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '6', 'A saber, que os gentios são co-herdeiros, e de um mesmo corpo, e participantes da promessa em Cristo pelo evangelho;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '7', 'Do qual fui feito ministro, pelo dom da graça de Deus, que me foi dado segundo a operação do seu poder.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '8', 'A mim, o mínimo de todos os santos, me foi dada esta graça de anunciar entre os gentios, por meio do evangelho, as riquezas incompreensíveis de Cristo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '9', 'E demonstrar a todos qual seja a dispensação do mistério, que desde os séculos esteve oculto em Deus, que tudo criou;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '10', 'Para que agora, pela igreja, a multiforme sabedoria de Deus seja conhecida dos principados e potestades nos céus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '11', 'Segundo o eterno propósito que fez em Cristo Jesus nosso SENHOR,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '12', 'No qual temos ousadia e acesso com confiança, pela nossa fé nele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '13', 'Portanto vos peço que não desfaleçais nas minhas tribulações por vós que são a vossa glória.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '14', 'Por causa disto me ponho de joelhos perante o Pai de nosso SENHOR Jesus Cristo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '15', 'Do qual toda a família nos céus e na terra toma o nome,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '16', 'Para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '17', 'Para que Cristo habite pela fé nos vossos corações; a fim de, estando arraigados e fundados em amor,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '18', 'Poderdes perfeitamente compreender, com todos os santos, qual seja a largura, e o comprimento, e a altura, e a profundidade,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '19', 'E conhecer o amor de Cristo, que excede todo o entendimento, para que sejais cheios de toda a plenitude de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '20', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '3', '21', 'A esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '1', 'ROGO-VOS, pois, eu, o preso do SENHOR, que andeis como é digno da vocação com que fostes chamados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '2', 'Com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '3', 'Procurando guardar a unidade do Espírito pelo vinculo da paz.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '4', 'Há um só corpo e um só Espirito, como também fostes chamados em uma só esperança da vossa vocação;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '5', 'Um só Senhor, uma só fé, um só baptismo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '6', 'Um só Deus e Pai de todos, o qual é sobre todos, e por todos e em todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '7', 'Mas a graça foi dada a cada um de nós segundo a medida do dom de Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '8', 'Pelo que diz: Subindo ao alto, levou cativo o cativeiro, e deu dons aos homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '9', 'Ora, isto - ele subiu - que é, senão que também antes tinha descido às partes mais baixas da terra?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '10', 'Aquele que desce é também o mesmo que subiu acima de todos os céus, para cumprir todas as coisas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '11', 'E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e doutores,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '12', 'Querendo o aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '13', 'Até que todos cheguemos à unidade da fé, e ao conhecimento do Filho de Deus, a varão perfeito, à medida da estatura completa de Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '14', 'Para que não sejamos mais meninos inconstantes, levados em roda por todo o vento de doutrina, pelo engano dos homens que com astúcia enganam fraudulosamente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '15', 'Antes, seguindo a verdade em caridade, cresçamos em tudo naquele que é a cabeça, Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '16', 'Do qual todo o corpo, bem ajustado, e ligado pelo auxílio de todas as juntas, segundo a justa operação de cada parte, faz o aumento do corpo, para sua edificação em amor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '17', 'E digo isto, e testifico no SENHOR, para que não andeis mais como andam também os outros gentios, na vaidade do seu sentido,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '18', 'Entenebrecidos no entendimento separados da vida de Deus pela ignorância que há neles, pela dureza do seu coração;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '19', 'Os quais, havendo perdido todo o sentimento, se entregaram à dissolução, para com avidez cometerem toda a impureza.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '20', 'Mas vós não aprendestes assim a Cristo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '21', 'Se é que o tendes ouvido, e nele fostes ensinados, como está a verdade em Jesus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '22', 'Que, quanto ao trato passado, vos despojeis do velho homem, que se corrompe pelas concupiscências do engano;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '23', 'E vos renoveis no espírito do vosso sentido;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '24', 'E vos revistais do novo homem, que segundo Deus é criado em verdadeira justiça e santidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '25', 'Pelo que deixai a mentira, e falai a verdade, cada um com o seu próximo; porque somos membros uns dos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '26', 'Irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '27', 'Não deis lugar ao diabo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '28', 'Aquele que furtava, não furte mais; antes trabalhe, fazendo com as mãos o que é bom, para que tenha que repartir com o que tiver necessidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '29', 'Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '30', 'E não entristeçais o Espírito Santo de Deus, no qual estais selados para o dia da redenção.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '31', 'Toda a amargura, e ira, e cólera, e gritaria, e blasfémia e toda a malícia seja tirada de entre vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '4', '32', 'Antes sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '1', 'SEDE pois imitadores de Deus, como filhos amados;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '2', 'E andai em amor, como também Cristo vos amou, e se entregou a si mesmo por nós, em oferta e sacrifício a Deus, em cheiro suave.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '3', 'Mas a prostituição, e toda a impureza ou avareza, nem ainda se nomeie entre vós, como convém a santos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '4', 'Nem torpezas, nem parvoíces, nem chocarrices, que não convêm; mas antes acções de graças.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '5', 'Porque bem sabeis isto: que nenhum devasso, ou impuro, ou avarento, o qual é idólatra, tem herança no reino de Cristo e de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '6', 'Ninguém vos engane com palavras vãs; porque por estas coisas vem a ira de Deus sobre os filhos da desobediência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '7', 'Portanto não sejais seus companheiros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '8', 'Porque noutro tempo éreis trevas, mas agora sois luz no SENHOR: andai como filhos da luz');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '9', '(Porque o fruto do Espírito está em toda a bondade, e justiça e verdade);');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '10', 'Aprovando o que é agradável ao SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '11', 'E não comuniqueis com as obras infrutuosas das trevas, mas antes condenai-as.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '12', 'Porque o que eles fazem em oculto até dizê-lo é torpe.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '13', 'Mas todas estas coisas se manifestam, sendo condenadas, pela luz, porque a luz tudo manifesta.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '14', 'Pelo que diz: Desperta, tu que dormes, e levanta-te de entre os mortos, e Cristo te esclarecerá.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '15', 'Portanto, vede prudentemente como andais, não como néscios, mas como sábios,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '16', 'Remindo o tempo; porquanto os dias são maus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '17', 'Pelo que não sejais insensatos, mas entendei qual seja a vontade do SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '18', 'E não vos embriagueis com vinho, em que há contenda, mas enchei-vos do Espirito;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '19', 'Falando entre vós em salmos, e hinos, e cânticos espirituais: cantando e salmodiando ao SENHOR no vosso coração;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '20', 'Dando sempre graças por tudo ao nosso Deus e Pai, em nome de nosso SENHOR Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '21', 'Sujeitando-vos uns aos outros no temor de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '22', 'Vós, mulheres, sujeitai-vos a vossos maridos, como ao SENHOR;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '23', 'Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '24', 'De sorte que, assim como a igreja está sujeita a Cristo, assim também as mulheres sejam em tudo sujeitas a seus maridos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '25', 'Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja, e a si mesmo se entregou por ela,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '26', 'Para a santificar, purificando-a com a lavagem da água, pela palavra,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '27', 'Para a apresentar a si mesmo igreja gloriosa, sem mácula, nem ruga, nem coisa semelhante, mas santa e irrepreensível.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '28', 'Assim devem os maridos amar a suas próprias mulheres, como a seus próprios corpos. Quem ama a sua mulher, ama-se a si mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '29', 'Porque nunca ninguém aborreceu a sua própria carne; antes a alimenta e sustenta, como também o SENHOR à igreja;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '30', 'Porque somos membros do seu corpo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '31', 'Por isso deixará o homem seu pai e sua mãe, e se unirá a sua mulher; e serão dois numa carne.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '32', 'Grande é este mistério: digo-o porém a respeito de Cristo e da igreja.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '5', '33', 'Assim também vós cada um em particular ame a sua própria mulher como a si mesmo, e a mulher reverencie o marido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '1', 'VÓS, filhos, sede obedientes a vossos pais no SENHOR, porque isto é justo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '2', 'Honra a teu pai e a tua mãe, que é o primeiro mandamento com promessa;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '3', 'Para que te vá bem, e vivas muito tempo sobre a terra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '4', 'E vós, pais, não provoqueis a ira a vossos filhos, mas criai-os na doutrina e admoestação do SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '5', 'Vós, servos, obedecei a vossos senhores segundo a carne, com temor e tremor, na sinceridade de vosso coração, como a Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '6', 'Não servindo à vista, como para agradar aos homens, mas como servos de Cristo, fazendo de coração a vontade de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '7', 'Servindo de boa vontade como ao SENHOR, e não como aos homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '8', 'Sabendo que cada um receberá do SENHOR todo o bem que fizer, seja servo, seja livre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '9', 'E vós senhores, fazei o mesmo para com eles, deixando as ameaças, sabendo também que o SENHOR deles e vosso está no céu, e que para com ele não há acepção de pessoas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '10', 'No demais, irmãos meus, fortalecei-vos no SENHOR e na força do seu poder.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '11', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '12', 'Porque não temos que lutar contra a carne e o sangue, mas sim contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '13', 'Portanto tomai toda a armadura de Deus, para que possais resistir no dia mau, e, havendo feito tudo, ficar firmes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '14', 'Estai pois firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '15', 'E calçados os pés na preparação do evangelho da paz,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '16', 'Tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '17', 'Tomai também o capacete da salvação, e espada do Espírito, que é a palavra de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '18', 'Orando em todo o tempo com toda a oração e súplica no Espírito, e vigiando nisto com toda a perseverança e súplica por todos os santos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '19', 'E por mim; para que me seja dada, no abrir da minha boca, a palavra com confiança, para fazer notório o mistério do evangelho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '20', 'Pelo qual sou embaixador em cadeias; para que possa falar dele livremente, como me convém falar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '21', 'Ora; para que vós também possais saber dos meus negócios, e o que eu faço, Tíquico, irmão amado, e fiel ministro do SENHOR, vos informará de tudo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '22', 'O qual vos enviei para o mesmo fim, para que saibais do nosso estado, e ele console os vossos corações.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '23', 'Paz seja com os irmãos, e caridade com fé da parte de Deus Pai e da do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('49', '6', '24', 'A graça seja com todos os que amam a nosso SENHOR Jesus Cristo em sinceridade. Ámen.');