INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '1', '¶ PAULO, e Silvano, e Timóteo, à igreja dos tessalonicenses, em Deus, o Pai, e no SENHOR Jesus Cristo: Graça e paz tenhais de Deus nosso Pai e do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '2', 'Sempre damos graças a Deus por vós todos, fazendo menção de vós em nossas orações;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '3', 'Lembrando-nos sem cessar da obra da vossa fé, do trabalho da caridade, e da paciência da esperança em Nosso SENHOR Jesus Cristo, diante de nosso Deus e Pai;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '4', 'Sabendo, amados irmãos, que a vossa eleição é de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '5', 'Porque o nosso evangelho não foi a vós somente em palavras, mas também em poder, e no Espirito Santo, e em muita certeza; como bem sabeis quais fomos entre vós, por amor de vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '6', 'E vós fostes feitos nossos imitadores, e do SENHOR, recebendo a palavra em muita tribulação, com gozo do Espírito Santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '7', 'De maneira que fostes exemplo para todos os fiéis na Macedónia e Acaia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '8', 'Porque por vós soou a palavra do SENHOR, não somente na Macedónia e Acaia, mas também em todos os lugares a vossa fé para com Deus se espalhou, de tal maneira que já dela não temos necessidade de falar coisa alguma;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '9', 'Porque eles mesmos anunciam de nós qual a entrada que tivemos para convosco, e como dos ídolos vos convertestes a Deus, para servir o Deus vivo e verdadeiro,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '1', '10', 'E esperar dos céus a seu Filho, a quem ressuscitou dos mortos, a saber, Jesus, que nos livra da ira futura.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '1', 'PORQUE vós mesmos, irmãos, bem sabeis que a nossa entrada para convosco não foi vã;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '2', 'Mas, havendo primeiro padecido, e sido agravados em Filipos, como sabeis, tornámo-nos ousados em nosso Deus, para vos falar o evangelho de Deus com grande combate.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '3', 'Porque a nossa exortação não foi com engano, nem com imundície, nem com fraudulência;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '4', 'Mas, como fomos aprovados de Deus para que o evangelho nos fosse confiado, assim falámos, não como para agradar aos homens, mas a Deus, que prova os nossos corações.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '5', 'Porque, como bem sabeis, nunca usámos de palavras lisonjeiras, nem houve um pretexto de avareza; Deus é testemunha;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '6', 'E não buscámos glória dos homens, nem de vós, nem de outros, ainda que podíamos, como apóstolos de Cristo, ser-vos pesados;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '7', 'Antes fomos brandos entre vós, como a ama que cria seus filhos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '8', 'Assim nós, sendo-vos tão afeiçoados, de boa vontade quiséramos comunicar-vos, não somente o evangelho de Deus, mas ainda as nossas próprias almas; porquanto nos éreis muito queridos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '9', 'Porque bem vos lembrais, irmãos, do nosso trabalho e fadiga; pois, trabalhando, noite e dia, para não sermos pesados a nenhum de vós, vos pregámos o evangelho de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '10', 'Vós e Deus sois testemunhas de quão santa, e justa, e irrepreensivelmente nos houvemos para convosco, os que crestes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '11', 'Assim como bem sabeis de que modo vos exortávamos e consolávamos, a cada um de vós, como o pai a seus filhos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '12', 'Para que vos conduzísseis dignamente para com Deus, que vos chama para o seu reino e glória.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '13', 'Pelo que também damos sem cessar graças a Deus, pois, havendo recebido de nós a palavra da pregação de Deus, a recebestes, não como palavra de homens, mas (segundo é, na verdade), como palavra de Deus, a qual também opera em vós, os que crestes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '14', 'Porque vós, irmãos, haveis sido feitos imitadores das igrejas de Deus que na Judeia estão em Jesus Cristo; porquanto também padecestes de vossos próprios concidadãos o mesmo que os judeus lhes fizeram a eles,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '15', 'Os quais também mataram o SENHOR Jesus e os seus próprios profetas, e nos têm perseguido; e não agradam a Deus, e são contrários a todos os homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '16', 'E nos impedem de pregar aos gentios as palavras da salvação, a fim de encherem sempre a medida de seus pecados; mas a ira de Deus caiu sobre eles até ao fim;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '17', 'Nós, porém, irmãos, sendo privados de vós por um momento de tempo, de vista, mas não do coração, tanto mais procurámos com grande desejo ver o vosso rosto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '18', 'Pelo que bem quisemos uma e outra vez ir ter convosco, pelo menos eu, Paulo, mas Satanás no-lo impediu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '19', 'Porque, qual é a nossa esperança, ou gozo, ou coroa de glória? Porventura não o sois vós também diante de nosso SENHOR Jesus Cristo em sua vinda?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '2', '20', 'Na verdade vós sois a nossa glória e gozo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '1', 'PELO que, não podendo esperar mais, de boamente quisemos deixar-nos ficar sós em Atenas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '2', 'E enviámos Timóteo, nosso irmão, e ministro de Deus, e nosso cooperador no evangelho de Cristo, para vos confortar e vos exortar acerca da vossa fé;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '3', 'Para que ninguém se comova por estas tribulações; porque vós mesmos sabeis que para isto fomos ordenados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '4', 'Pois, estando ainda convosco, vos predizíamos que havíamos de ser afligidos, como sucedeu, e vós o sabeis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '5', 'Portanto, não podendo eu também esperar mais, mandei-o saber da vossa fé, temendo que o tentador vos tentasse, e o nosso trabalho viesse a ser inútil.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '6', 'Vindo, porém, agora Timóteo de vós para nós, e trazendo-nos boas novas da vossa fé e caridade, e de como sempre tendes boa lembrança de nós, desejando muito ver-nos, como nós também a vós;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '7', 'Por esta razão, irmãos, ficámos consolados acerca de vós, em toda a nossa aflição e necessidade, pela vossa fé,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '8', 'Porque agora vivemos, se estais firmes no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '9', 'Porque, que acção de graças poderemos dar a Deus por vós, por todo o gozo com que nos regozijamos por vossa causa diante do nosso Deus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '10', 'Orando abundantemente dia e noite, para que possamos ver o vosso rosto, e supramos o que falta à vossa fé?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '11', 'Ora o mesmo nosso Deus e Pai, e nosso SENHOR Jesus Cristo, encaminhe a nossa viagem para vós,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '12', 'E o SENHOR vos aumente, e faça abundar em caridade uns para com os outros, e para com todos, como também abundamos para convosco;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '3', '13', 'Para confortar os vossos corações, para que sejais irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso SENHOR Jesus Cristo com todos os seus santos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '1', 'FINALMENTE, irmãos, vos rogamos e exortamos no SENHOR Jesus, que, assim como recebestes de nós, de que maneira convém andar e agradar a Deus, assim andai, para que possais progredir cada vez mais.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '2', 'Porque vós bem sabeis que mandamentos vos temos dado pelo SENHOR Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '3', 'Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '4', 'Que cada um de vós saiba possuir o seu vaso em santificação e honra;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '5', 'Não na paixão de concupiscência, como os gentios, que não conhecem a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '6', 'Ninguém oprima ou engane a seu irmão em negócio algum, porque o SENHOR é vingador de todas estas coisas, como também antes vo-lo dissemos e testificámos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '7', 'Porque não nos chamou Deus para a imundície, mas para a santificação:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '8', 'Portanto, quem despreza isto não despreza ao homem, mas sim a Deus, que nos deu também o seu Espírito Santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '9', 'Quanto, porém, ao amor fraternal, não necessitais de que vos escreva, visto que vós mesmos estais instruídos por Deus que vos ameis uns aos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '10', 'Porque também já assim o fazeis para com todos os irmãos que estão por toda a Macedónia. Exortamo-vos, porém, a que ainda nisto abundeis cada vez mais,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '11', 'E procureis viver quietos, e tratar dos vossos próprios negócios, e trabalhar com vossas próprias mãos, como já vo-lo temos mandado;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '12', 'Para que andeis honestamente para com os que estão de fora, e não necessiteis de coisa alguma.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '13', 'Não quero, porém, irmãos, que sejais ignorantes acerca dos que já dormem, para que não vos entristeçais, como os demais, que não têm esperança.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '14', 'Porque, se cremos que Jesus morreu e ressuscitou, assim também, aos que em Jesus dormem, Deus os tornará a trazer com ele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '15', 'Dizemo-vos, pois, isto pela palavra do SENHOR: que nós, os que ficarmos vivos para a vinda do SENHOR, não precederemos os que dormem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '16', 'Porque o mesmo SENHOR descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '17', 'Depois nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o SENHOR nos ares, e assim estaremos sempre com o SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '4', '18', 'Portanto, consolai-vos uns aos outros com estas palavras.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '1', 'MAS, irmãos, acerca dos tempos e das estações, não necessitais de que se vos escreva;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '2', 'Porque vós mesmos sabeis muito bem que o dia do SENHOR virá como o ladrão de noite;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '3', 'Pois que, quando disserem: Há paz e segurança; então lhes sobrevirá repentina destruição, como as dores de parto àquela que está grávida; e de modo nenhum escaparão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '4', 'Mas vós, irmãos, já não estais em trevas, para que aquele dia vos surpreenda como um ladrão;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '5', 'Porque todos vós sois filhos da luz e filhos do dia; nós não somos da noite nem das trevas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '6', 'Não durmamos pois, como os demais, mas vigiemos, e sejamos sóbrios,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '7', 'Porque os que dormem dormem de noite, e os que se embebedam, embebedam-se de noite.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '8', 'Mas nós, que somos do dia, sejamos sóbrios, vestindo-nos da couraça da fé e da caridade, e tendo por capacete a esperança da salvação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '9', 'Porque Deus não nos destinou para a ira, mas para a aquisição da salvação, por nosso SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '10', 'Que morreu por nós, para que, quer vigiemos, quer durmamos, vivamos juntamente com ele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '11', 'Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como também o fazeis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '12', 'E rogamo-vos, irmãos, que reconheçais os que trabalham entre vós e que presidem sobre vós no SENHOR, e vos admoestam;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '13', 'E que os tenhais em grande estima e amor, por causa da sua obra. Tende paz entre vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '14', 'Rogamo-vos também, irmãos, que admoesteis os desordeiros, consoleis os de pouco ânimo, sustenteis os fracos, e sejais pacientes para com todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '15', 'Vede que ninguém dê a outrem mal por mal, mas segui sempre o bem, tanto uns para com os outros, como para com todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '16', 'Regozijai-vos sempre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '17', 'Orai sem cessar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '18', 'Em tudo dai graças; porque esta é a vontade de Deus em Cristo Jesus para convosco.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '19', 'Não extingais o Espírito.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '20', 'Não desprezeis as profecias;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '21', 'Examinai tudo. Retende o bem;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '22', 'Abstende-vos de toda a aparência do mal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '23', 'E o mesmo Deus de paz vos santifique em tudo; e todo o vosso espírito e alma, e corpo, sejam plenamente conservados irrepreensíveis para a vinda de nosso SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '24', 'Fiel é o que vos chama, o qual também o fará.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '25', 'Irmãos, orai por nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '26', 'Saudai a todos os irmãos em ósculo santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '27', 'Pelo SENHOR vos conjuro que esta epístola seja lida a todos os santos irmãos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('52', '5', '28', 'A graça de nosso SENHOR Jesus Cristo seja convosco. Ámen.');