INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '1', '¶ PAULO, e Silvano, e Timóteo, à igreja dos tessalonicenses, em Deus nosso Pai e no SENHOR Jesus Cristo:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '2', 'Graça e paz a vós da parte de Deus nosso Pai, e da do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '3', 'Sempre devemos, irmãos, dar graças a Deus por vós, como é de razão, porque a vossa fé cresce muitíssimo e a caridade de cada um de vós abunda de uns para com os outros,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '4', 'De maneira que nós mesmos nos gloriamos de vós nas igrejas de Deus por causa da vossa paciência e fé, e em todas as vossas perseguições e aflições que suportais;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '5', 'Prova clara do justo juízo de Deus, para que sejais havidos por dignos do reino de Deus, pelo qual também padeceis;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '6', 'Se de facto é justo diante de Deus que dê em paga tribulação aos que vos atribulam,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '7', 'E a vós, que sois atribulados, descanso connosco quando se manifestar o SENHOR Jesus desde o céu com os anjos do seu poder,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '8', 'Como labareda de fogo, tomando vingança dos que não conhecem a Deus e dos que não obedecem ao evangelho de nosso SENHOR Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '9', 'Os quais por castigo padecerão eterna perdição, ante a face do SENHOR e a glória do seu poder,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '10', 'Quando vier para ser glorificado nos seus santos, e para se fazer admirável naquele dia em todos os que crêem (porquanto o nosso testemunho foi crido entre vós).');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '11', 'Pelo que também rogamos sempre por vós, para que o nosso Deus vos faça dignos da sua vocação, e cumpra todo o desejo da sua bondade, e a obra da fé com poder;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '1', '12', 'Para que o nome de nosso SENHOR Jesus Cristo seja em vós glorificado, e vós nele, segundo a graça de nosso Deus e do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '1', 'ORA, irmãos, rogamo-vos, pela vinda de nosso SENHOR Jesus Cristo, e pela nossa reunião com ele,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '2', 'Que não vos movais facilmente do vosso entendimento, nem vos perturbeis, quer por espírito, quer por palavra, quer por epístola, como de nós, como se o dia de Cristo estivesse já perto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '3', 'Ninguém de maneira alguma vos engane; porque não será assim sem que antes venha a apostasia, e se manifeste o homem do pecado, o filho da perdição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '4', 'O qual se opõe, e se levanta contra tudo o que se chama Deus, ou se adora; de sorte que se assentará, como Deus, no templo de Deus, querendo parecer Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '5', 'Não vos lembrais de que estas coisas vos dizia quando ainda estava convosco?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '6', 'E agora vós sabeis o que o detém, para que a seu próprio tempo seja manifestado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '7', 'Porque já o mistério da injustiça opera; somente há um que agora resiste até que do meio seja tirado;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '8', 'E então será revelado o iníquo, a quem o SENHOR desfará pelo assopro da sua boca, e aniquilará pelo esplendor da sua vinda;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '9', 'A esse cuja vinda é segundo a eficácia de Satanás, com todo o poder e sinais e prodígios de mentira,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '10', 'E com todo o engano da injustiça para os que perecem, porque não receberam o amor da verdade para se salvarem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '11', 'E por isso Deus lhes enviará a operação do erro, para que creiam a mentira;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '12', 'Para que sejam julgados todos os que não creram a verdade, antes tiveram prazer na iniquidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '13', 'Mas devemos sempre dar graças a Deus por vós, irmãos amados do SENHOR, por vos ter Deus elegido desde o princípio para a salvação, em santificação do Espírito, e fé da verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '14', 'Para o que pelo nosso evangelho vos chamou, para alcançardes a glória de nosso SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '15', 'Então, irmãos, estai firmes e retende as tradições que vos foram ensinadas, seja por palavra, seja por epístola nossa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '16', 'E o próprio nosso SENHOR Jesus Cristo nosso Deus e Pai, que nos amou, e em graça nos deu uma eterna consolação e boa esperança,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '2', '17', 'Console os vossos corações, e vos conforte em toda a boa palavra e obra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '1', 'NO demais, irmãos, rogai por nós, para que a palavra do SENHOR tenha livre curso e seja glorificada, como também o é entre vós;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '2', 'E para que sejamos livres de homens dissolutos e maus; porque a fé não é de todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '3', 'Mas fiel é o SENHOR, que vos confortará, e guardará do maligno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '4', 'E confiamos de vós no SENHOR que não só fazeis, como fareis o que vos mandamos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '5', 'Ora o SENHOR encaminhe os vossos corações na caridade de Deus, e na paciência de Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '6', 'Mandamo-vos, porém, irmãos, em nome de nosso SENHOR Jesus Cristo, que vos aparteis de todo o irmão que andar desordenadamente, e não segundo a tradição que de nós recebeu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '7', 'Porque vós mesmos sabeis como convém imitar-nos, pois que não nos houvemos desordenadamente entre vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '8', 'Nem de graça comemos o pão de homem algum, mas com trabalho e fadiga, trabalhando noite e dia, para não sermos pesados a nenhum de vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '9', 'Não porque não tivéssemos autoridade, mas para vos dar em nós mesmos exemplo, para nos imitardes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '10', 'Porque, quando ainda estávamos convosco, vos mandámos isto, que, se alguém não quiser trabalhar, não coma também.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '11', 'Porquanto ouvimos que alguns entre vós andam desordenadamente, não trabalhando, antes fazendo coisas vãs.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '12', 'A esses tais, porém, mandamos, e exortamos por nosso SENHOR Jesus Cristo, que, trabalhando com sossego, comam o seu próprio pão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '13', 'E vós, irmãos, não vos canseis de fazer bem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '14', 'Mas, se alguém não obedecer à nossa palavra por esta carta, notai o tal, e não vos mistureis com ele, para que se envergonhe.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '15', 'Todavia não o tenhais como inimigo, mas admoestai-o como irmão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '16', 'Ora o mesmo SENHOR da paz vos dê sempre paz de toda a maneira. O SENHOR seja com todos vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '17', 'Saudação da minha própria mão, de mim, Paulo, que é o sinal em todas as epístolas: assim escrevo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('53', '3', '18', 'A graça de nosso SENHOR Jesus Cristo seja com todos vós. Ámen.');