INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '1', '¶ PAULO, apóstolo de Jesus Cristo segundo o mandado de Deus, nosso Salvador, e do SENHOR Jesus Cristo, esperança nossa,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '2', 'A Timóteo meu verdadeiro filho na fé: graça, misericórdia e paz da parte de Deus nosso Pai e de Cristo Jesus, nosso SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '3', 'Como te roguei, quando parti para a Macedónia, que ficasses em Éfeso, para advertires a alguns, que não ensinem outra doutrina,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '4', 'Nem se dêem a fábulas ou a genealogias intermináveis, que mais produzem questões do que edificação de Deus, que consiste na fé; assim, o faço agora.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '5', 'Ora o fim do mandamento é a caridade de um coração puro, e de uma boa consciência, e de uma fé não fingida:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '6', 'Do que desviando-se alguns, se entregaram a vãs contendas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '7', 'Querendo ser doutores da lei, e não entendendo nem o que dizem, nem o que afirmam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '8', 'Sabemos, porém, que a lei é boa, se alguém dela usa legitimamente;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '9', 'Sabendo isto, que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '10', 'Para os devassos, para os sodomitas, para os roubadores de homens, para os mentirosos, para as perjuros, e para o que for contrário à sã doutrina,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '11', 'Conforme o evangelho da glória de Deus bem-aventurado, que me foi confiado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '12', 'E dou graças ao que me tem confortado, a Cristo Jesus Senhor nosso, porque me teve por fiel, pondo-me no ministério;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '13', 'A mim, que dantes fui blasfemo, e perseguidor, e opressor; mas alcancei misericórdia, porque o fiz ignorantemente, na incredulidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '14', 'E a graça de nosso SENHOR superabundou com a fé e amor que há em Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '15', 'Esta é uma palavra fiel, e digna de toda a aceitação, que Cristo Jesus veio ao mundo, para salvar os pecadores, dos quais eu sou o principal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '16', 'Mas por isso alcancei misericórdia, para que em mim, que sou o principal, Jesus Cristo mostrasse toda a sua longanimidade, para exemplo dos que haviam de crer nele para a vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '17', 'Ora ao Rei dos séculos, imortal, invisível, ao único Deus seja honra e glória para todo o sempre. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '18', 'Este mandamento te dou, meu filho Timóteo, que, segundo as profecias que houve acerca de ti, milites por elas boa milícia;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '19', 'Conservando a fé, e a boa consciência, rejeitando a qual alguns fizeram naufrágio na fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '1', '20', 'E entre esses foram Himeneu e Alexandre, os quais entreguei a Satanás, para que aprendam a não blasfemar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '1', 'ADMOESTO-TE pois, antes de tudo, que se façam deprecações, orações, intercessões, e acções de graças por todos os homens;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '2', 'Pelos reis, e por todos os que estão em eminência, para que tenhamos uma vida quieta e sossegada, em toda a piedade e honestidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '3', 'Porque isto é bom e agradável diante de Deus nosso Salvador,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '4', 'Que quer que todos os homens se salvem, e venham ao conhecimento da verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '5', 'Porque há um só Deus, e um só Mediador entre Deus e os homens, Jesus Cristo homem,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '6', 'O qual se deu a si mesmo em preço de redenção por todos, para servir de testemunho a seu tempo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '7', 'Para o que (digo a verdade em Cristo, não minto) fui constituído pregador, e apóstolo, e doutor dos gentios na fé e na verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '8', 'Quero pois que os homens orem em todo o lugar, levantando mãos santas, sem ira nem contenda.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '9', 'Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '10', 'Mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '11', 'A mulher aprenda em silêncio, com toda a sujeição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '12', 'Não permito, porém, que a mulher ensine, nem use de autoridade sobre o marido, mas que esteja em silêncio.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '13', 'Porque primeiro foi formado Adão, depois Eva.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '14', 'E Adão não foi enganado, mas a mulher, sendo enganada, caiu em transgressão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '2', '15', 'Salvar-se-á, porém, dando à luz na fé, na caridade e na santificação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '1', 'ESTA é uma palavra fiel: se alguém deseja o episcopado, excelente obra deseja.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '2', 'Convém pois que o bispo seja irrepreensível, marido de uma mulher, vigilante, sério, honesto, hospitaleiro, apto para ensinar;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '3', 'Não dado ao vinho, não espancador, não cobiçoso de torpe ganância, mas moderado, não contencioso, não avarento;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '4', 'Que governe bem a sua própria casa, tendo seus filhos em sujeição, com toda a modéstia;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '5', '(Porque, se alguém não sabe governar a sua própria casa, terá cuidado da igreja de Deus?)');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '6', 'Não neófito, para que, ensoberbecendo-se, não caia na condenação do diabo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '7', 'Convém também que tenha bom testemunho dos que estão de fora, para que não caia em afronta, e no laço do diabo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '8', 'Da mesma sorte os diáconos sejam honestos, não de língua dobre, não dados a muito vinho, não cobiçosos de torpe ganância;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '9', 'Guardando o mistério da fé em uma pura consciência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '10', 'E também estes sejam primeiro provados, depois sirvam, se forem irrepreensíveis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '11', 'Da mesma sorte as mulheres sejam honestas, não maldizentes, sóbrias e fieis em tudo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '12', 'Os diáconos sejam maridos de uma mulher, e governem bem a seus filhos e suas próprias casas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '13', 'Porque os que servirem bem como diáconos, adquirirão para si uma boa posição, e muita confiança na fé que há em Cristo Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '14', 'Escrevo-te estas coisas, esperando ir ver-te bem depressa;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '15', 'Mas, se tardar, para que saibas como convém andar na casa de Deus, que é a igreja do Deus vivo, a coluna e firmeza da verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '3', '16', 'E sem dúvida alguma grande é o mistério da piedade: Aquele que se manifestou em carne, foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo, e recebido acima na glória.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '1', 'MAS o Espírito expressamente diz que nos últimos tempos apostatarão alguns da fé, dando ouvidos a espíritos enganadores, e a doutrinas de demónios;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '2', 'Pela hipocrisia de homens que falam mentiras, tendo cauterizada a sua própria consciência;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '3', 'Proibindo o casamento, e ordenando a abstinência dos manjares que Deus criou para os fiéis, e para os que conhecem a verdade, a fim de usarem deles com acções de graças;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '4', 'Porque toda a criatura de Deus é boa, e não há nada que rejeitar, sendo recebido com acções de graças.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '5', 'Porque pela palavra de Deus e pela oração é santificada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '6', 'Propondo estas coisas aos irmãos, serás bom ministro de Jesus Cristo, criado com as palavras da fé e da boa doutrina que tens seguido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '7', 'Mas rejeita as fábulas profanas e de velhas, e exercita-te a ti mesmo em piedade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '8', 'Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '9', 'Esta palavra é fiel e digna de toda a aceitação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '10', 'Porque para isto trabalhamos e lutamos, pois esperamos no Deus vivo, que é o salvador de todos os homens, principalmente dos fiéis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '11', 'Manda estas coisas e ensina-as.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '12', 'Ninguém despreze a tua mocidade: mas sê o exemplo dos fiéis, na palavra, no trato, na caridade, no espírito, na fé, na pureza.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '13', 'Persiste em ler, exortar e ensinar, até que eu vá.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '14', 'Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbitério.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '15', 'Medita estas coisas; ocupa-te nelas, para que o teu aproveitamento seja manifesto a todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '4', '16', 'Tem cuidado de ti mesmo e da doutrina: persevera nestas coisas; porque, fazendo isto, te salvarás, tanto a ti mesmo como aos que te ouvem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '1', 'NÃO repreendas asperamente os anciãos, mas admoesta-os como a pais, aos mancebos como a irmãos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '2', 'Às mulheres idosas, como a mães, às moças, como a irmãs, em toda a pureza.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '3', 'Honra as viúvas que verdadeiramente são viúvas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '4', 'Mas, se alguma viúva tiver filhos, ou netos, aprendam primeiro a exercer piedade para com a sua própria família, e a recompensar seus pais; porque isto é bom e agradável diante de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '5', 'Ora a que é verdadeiramente viúva e desamparada espera em Deus, e persevera de noite e de dia em rogos e orações;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '6', 'Mas a que vive em deleites, vivendo está morta.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '7', 'Manda, pois, estas coisas, para que elas sejam irrepreensíveis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '8', 'Mas, se alguém não tem cuidado dos seus, e principalmente dos da sua família, negou a fé, e é pior do que o infiel.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '9', 'Nunca seja inscrita viúva com menos de sessenta anos, e só a que tenha sido mulher de um só marido;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '10', 'Tendo testemunho de boas obras se criou os filhos, se exercitou hospitalidade, se lavou os pés aos santos, se socorreu os aflitos, se praticou toda a boa obra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '11', 'Mas não admitas as viúvas mais novas, porque quando se tornam levianas contra Cristo, querem casar-se;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '12', 'Tendo já a sua condenação por haverem aniquilado a primeira fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '13', 'E, além disto, aprendem também a andar ociosas de casa em casa; e não só ociosas, mas também paroleiras e curiosas, falando o que não convém.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '14', 'Quero pois que as que são moças se casem, gerem filhos, governem a casa, e não dêem ocasião ao adversário de maldizer.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '15', 'Porque já algumas se desviaram, indo após Satanás.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '16', 'Se algum crente ou alguma crente tem viúvas, socorra-as, e não se sobrecarregue a igreja, para que se possam sustentar as que deveras são viúvas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '17', 'Os presbíteros que governam bem sejam estimados por dignos de duplicada honra, principalmente os que trabalham na palavra e na doutrina.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '18', 'Porque diz a Escritura: Não ligarás a boca ao boi que debulha. E: Digno é o obreiro do seu salário.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '19', 'Não aceites acusação contra o presbítero senão com duas ou três testemunhas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '20', 'Aos que pecarem, repreende-os na presença de todos, para que também os outros tenham temor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '21', 'Conjuro-te diante de Deus, e do SENHOR Jesus Cristo, e dos anjos eleitos, que sem prevenção guardes estas coisas, nada fazendo por parcialidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '22', 'A ninguém imponhas precipitadamente as mãos, nem participes dos pecados alheios: conserva-te a ti mesmo puro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '23', 'Não bebas mais água só, mas usa de um pouco de vinho, por causa do teu estômago e das tuas frequentes enfermidades.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '24', 'Os pecados de alguns homens são manifestos precedendo o juízo; e em alguns manifestam-se depois.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '5', '25', 'Assim mesmo também as boas obras são manifestas, e as que são doutra maneira não podem ocultar-se.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '1', 'TODOS os servos que estão debaixo do jugo estimem a seus senhores por dignos de toda a honra, para que o nome de Deus e a doutrina não sejam blasfemados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '2', 'E os que têm senhores crentes não os desprezem, por serem irmãos; antes os sirvam melhor, porque eles, que participam do benefício, são crentes e amados. Isto ensina e exorta.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '3', 'Se alguém ensina alguma outra doutrina, e se não conforma com as sãs palavras de nosso SENHOR Jesus Cristo, e com a doutrina que é segundo a piedade,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '4', 'É soberbo, e nada sabe, mas delira acerca de questões e contendas de palavras, das quais nascem invejas, porfias, blasfémias, ruins suspeitas,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '5', 'Contendas de homens corruptos de entendimento, e privados da verdade, cuidando que a piedade seja causa de ganho: aparta-te dos tais.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '6', 'Mas é grande ganho a piedade com contentamento.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '7', 'Porque nada trouxemos para este mundo, e manifesto é que nada podemos levar dele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '8', 'Tendo, porém, sustento, e com que nos cobrirmos, estejamos com isso contentes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '9', 'Mas os que querem ser ricos caem em tentação e em laços, e em muitas concupiscências loucas e nocivas, que submergem os homens na perdição e ruína.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '10', 'Porque o amor do dinheiro é a raiz de toda a espécie de males; e nessa cobiça alguns se desviaram da fé, e se traspassaram a si mesmo com muitas dores.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '11', 'Mas tu, ó homem de Deus, foge destas coisas, e segue a justiça, a piedade, a fé, a caridade, a paciência, a mansidão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '12', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '13', 'Mando-te diante de Deus, que todas as coisas vivifica; e de Cristo Jesus, que diante de Pôncio Pilatos deu o testemunho de boa confissão,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '14', 'Que guardes este mandamento sem mácula e repreensão, até à aparição de nosso SENHOR Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '15', 'A qual a seu tempo mostrará o bem-aventurado, e único poderoso SENHOR, Rei dos reis e Senhor dos senhores;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '16', 'Aquele que tem, ele só, a imortalidade, e habita na luz inacessível; a quem nenhum dos homens viu nem pode ver, ao qual seja honra e poder sempiterno. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '17', 'Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas para delas gozarmos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '18', 'Que façam bem, enriqueçam em boas obras, repartam de boamente, e sejam comunicáveis;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '19', 'Que entesourem para si mesmos um bom fundamento para o futuro, para que possam alcançar a vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '20', 'Ó Timóteo, guarda o depósito que te foi confiado, tendo horror aos clamores vãos e profanos e às oposições da falsamente chamada ciência,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('54', '6', '21', 'A qual professando-a alguns, se desviaram da fé. A graça seja contigo. Ámen.');