INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '1', '¶ PAULO, servo de Deus, e apóstolo de Jesus Cristo, segundo a fé dos eleitos de Deus, e o conhecimento da verdade, que é segundo a piedade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '2', 'Em esperança da vida eterna, a qual Deus, que não pode mentir, prometeu antes dos tempos dos séculos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '3', 'Mas a seu tempo manifestou a sua palavra pela pregação que me foi confiada segundo o mandamento de Deus; nosso salvador;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '4', 'A Tito, meu verdadeiro filho, segundo a fé comum, graça, misericórdia, e paz da parte de Deus Pai, e da do SENHOR Jesus Cristo, nosso Salvador.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '5', 'Por esta causa te deixei em Creta, para que pusesses em boa ordem as coisas que ainda restam, e de cidade em cidade estabelecesses presbíteros, como já te mandei;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '6', 'Aquele que for irrepreensível, marido de uma mulher, que tenha filhos fiéis, que não possam ser acusados de dissolução, nem sejam desobedientes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '7', 'Porque convém que o bispo seja irrepreensível, como dispenseiro de casa de Deus, não soberbo, nem iracundo, nem dado ao vinho, nem espancador, nem cobiçoso de torpe ganância;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '8', 'Mas dado à hospitalidade, amigo do bem, moderado, justo, santo, temperante;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '9', 'Retendo firme a fiel palavra, que é conforme a doutrina, para que seja poderoso, tanto para admoestar com a sã doutrina, como para convencer os contradizentes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '10', 'Porque há muitos desordenados, faladores, vãos e enganadores, principalmente os da circuncisão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '11', 'Aos quais convém tapar a boca; homens que transtornam casas inteiras ensinando o que não convém, por torpe ganância.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '12', 'Um deles, seu próprio profeta, disse: Os cretenses são sempre mentirosos, bestas ruins, ventres preguiçosos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '13', 'Este testemunho é verdadeiro. Portanto repreende-os severamente, para que sejam sãos na fé,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '14', 'Não dando ouvidos às fábulas judaicas, nem aos mandamentos de homens que se desviam da verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '15', 'Todas as coisas são puras para os puros, mas nada é puro para os contaminados e infiéis: antes o seu entendimento e consciência estão contaminados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '1', '16', 'Confessam que conhecem a Deus, mas negam-no com as obras, sendo abomináveis, e desobedientes, e reprovados para toda a boa obra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '1', 'TU, porém, fala o que convém à sã doutrina.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '2', 'Os velhos que sejam sóbrios, graves, prudentes, sãos na fé, na caridade, e na paciência;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '3', 'As mulheres idosas, semelhantemente, que sejam sérias no seu viver, como convém a santas, não caluniadoras, não dadas a muito vinho, mestras no bem;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '4', 'Para que ensinem as mulheres novas a serem prudentes, a amarem seus maridos, a amarem seus filhos,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '5', 'A serem moderadas, castas, boas donas de casa, sujeitas a seus maridos, a fim de que a palavra de Deus não seja blasfemada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '6', 'Exorta semelhantemente os mancebos a que sejam moderados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '7', 'Em tudo te dá por exemplo de boas obras; na doutrina mostra incorrupção, gravidade, sinceridade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '8', 'Linguagem sã e irrepreensível, para que o adversário se envergonhe, não tendo nenhum mal que dizer de nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '9', 'Exorta os servos a que se sujeitem a seus senhores, e em tudo agradem, não contradizendo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '10', 'Não defraudando, antes mostrando toda a boa lealdade, para que em tudo sejam ornamento da doutrina de Deus, nosso Salvador.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '11', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '12', 'Ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, e justa e piamente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '13', 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso SENHOR, Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '14', 'O qual se deu a si mesmo por nós para nos remir de toda a iniquidade, e purificar para si um povo seu especial, zeloso de boas obras.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '2', '15', 'Fala disto, e exorta e repreende com toda a autoridade. Ninguém te despreze.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '1', 'ADMOESTA-OS a que se sujeitem aos principados e potestades, que lhes obedeçam, e estejam preparados para toda a boa obra;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '2', 'Que a ninguém infamem, nem sejam contenciosos, mas modestos, mostrando toda a mansidão para com todos os homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '3', 'Porque também nós éramos noutro tempo insensatos, desobedientes, extraviados, servindo a várias concupiscências e deleites, vivendo em malícia e inveja, odiosos, odiando-nos uns aos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '4', 'Mas quando apareceu a benignidade e caridade de Deus, nosso Salvador, para com os homens,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '5', 'Não pelas obras de justiça que houvéssemos feito, mas segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '6', 'Que abundantemente ele derramou sobre nós por Jesus Cristo nosso Salvador;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '7', 'Para que, sendo justificados pela sua graça, sejamos feitos herdeiros segundo a esperança da vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '8', 'Fiel é a palavra, e isto quero que deveras afirmes, para que os que crêem em Deus procurem aplicar-se às boas obras; estas coisas são boas e proveitosas aos homens.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '9', 'Mas não entres em questões loucas, genealogias e contendas, e nos debates acerca da lei; porque são coisas inúteis e vãs.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '10', 'Ao homem herege, depois de uma e outra admoestação, evita-o.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '11', 'Sabendo que esse tal está pervertido, e peca, estando já em si mesmo condenado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '12', 'Quando te enviar Ártemas, ou Tíquico, procura vir ter comigo a Nicópolis; porque deliberei invernar ali.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '13', 'Acompanha com muito cuidado Zenas, doutor da lei, e Apolo, para que nada lhes falte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '14', 'E os nossos aprendam também a aplicar-se às boas obras, nas coisas necessárias, para que não sejam infrutuosos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('56', '3', '15', 'Saúdam-te todos os que estão comigo. Saúda tu os que nos amam na fé. A graça seja com vós todos. Ámen.');