INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '1', '¶ PAULO, prisioneiro de Jesus Cristo, e o irmão Timóteo, ao amado Filémon, nosso cooperador,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '2', 'E à nossa irmã Afia, e a Arquipo, nosso camarada, e à igreja que está em tua casa:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '3', 'Graça a vós e paz da parte de Deus nosso Pai, e da do SENHOR Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '4', 'Graças dou ao meu Deus, lembrando-me sempre de ti nas minhas orações;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '5', 'Ouvindo a tua caridade e a fé que tens para com o SENHOR Jesus Cristo, e para com todos os santos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '6', 'Para que a comunicação da tua fé seja eficaz no conhecimento de todo o bem que em vós há por Cristo Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '7', 'Tive grande gozo e consolação da tua caridade, porque por ti, ó irmão, as entranhas dos santos foram recriadas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '8', 'Pelo que, ainda que tenha em Cristo grande confiança para te mandar o que te convém,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '9', 'Todavia peço-te antes por caridade, sendo eu tal como sou, Paulo o velho, e também agora prisioneiro de Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '10', 'Peço-te por meu filho Onésimo, que gerei nas minhas prisões;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '11', 'O qual noutro tempo te foi inútil, mas agora a ti e a mim muito útil; eu to tornei a enviar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '12', 'E tu torna a recebê-lo como às minhas entranhas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '13', 'Eu bem o quisera conservar comigo, para que por ti me servisse nas prisões do evangelho;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '14', 'Mas nada quis fazer sem o teu parecer, para que o teu benefício não fosse como por força, mas voluntário.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '15', 'Porque bem pode ser que ele se tenha separado de ti por algum tempo, para que o retivesses para sempre,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '16', 'Não já como servo, antes, mais do que servo, como irmão amado, particularmente de mim: e quanto mais de ti, assim na carne como no SENHOR?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '17', 'Assim pois, se me tens por companheiro, recebe-o como a mim mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '18', 'E, se te fez algum dano, ou te deve alguma coisa, põe isso à minha conta.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '19', 'Eu, Paulo, de minha própria mão o escrevi; eu o pagarei, para te não dizer que ainda mesmo a ti próprio a mim te deves.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '20', 'Sim, irmão, eu me regozijarei de ti no SENHOR: recreia as minhas entranhas no SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '21', 'Escrevi-te confiado na tua obediência, sabendo que ainda farás mais do que digo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '22', 'E juntamente prepara-me também pousada, porque espero que pelas vossas orações vos hei de ser concedido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '23', 'Saúdam-te Epafras, meu companheiro de prisão por Cristo Jesus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '24', 'Marcos, Aristarco, Demas e Lucas, meus cooperadores.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('57', '1', '25', 'A graça de nosso SENHOR Jesus Cristo seja com o vosso espírito. Ámen');