INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '1', '¶ HAVENDO Deus antigamente falado muitas vezes, e de muitas maneiras, aos pais pelos profetas, a nós falou-nos nestes últimos dias pelo Filho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '2', 'A quem constituiu herdeiro de tudo, por quem fez também o mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '3', 'O qual, sendo o resplendor da sua glória, e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação das nossos pecados, assentou-se à dextra da majestade nas altura;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '4', 'Feito tanto mais excelente do que os anjos, quanto herdou mais excelente nome do que eles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '5', 'Porque, a qual dos anjos disse jamais: Tu és meu Filho, hoje te gerei? E outra vez: Eu lhe serei por Pai, e ele me será por Filho?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '6', 'E quando outra vez introduz no mundo o primogénito, diz: E todos os anjos de Deus o adorem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '7', 'E, quanto aos anjos, diz: O que de seus anjos faz ventos, e de seus ministros labareda de fogo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '8', 'Mas, do Filho, diz: Ó Deus, o teu trono subsiste pelos séculos dos séculos, cetro de equidade é o cetro do teu reino.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '9', 'Amaste a justiça e aborreceste a iniquidade; por isso Deus, o teu Deus te ungiu com óleo de alegria mais do que a teus companheiros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '10', 'E Tu, Senhor, no princípio fundaste a terra, e os céus são obra de tuas mãos:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '11', 'Eles perecerão, mas tu permanecerás; e todos eles, como roupa, envelhecerão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '12', 'E como um manto os enrolarás, e como um vestido se mudarão, mas tu és o mesmo, e os teus anos não acabarão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '13', 'E a qual dos anjos disse jamais: Assenta-te à minha dextra até que ponha a teus inimigos por escabelo de teus pés?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '1', '14', 'Não são porventura todos eles espíritos ministradores, enviados para servir a favor daqueles que hão de herdar a salvação?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '1', 'PORTANTO convém-nos atentar com mais diligência para as coisas que já temos ouvido, para que em tempo algum nos desviemos delas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '2', 'Porque, se a palavra falada pelos anjos permaneceu firme, e toda a transgressão e desobediência recebeu a justa retribuição,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '3', 'Como escaparemos nós, se não atentarmos para uma tão grande salvação, a qual, começando a ser anunciada pelo SENHOR, foi-nos depois confirmada pelos que a ouviram;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '4', 'Testificando também Deus com eles, por sinais, e milagres, e várias maravilhas e dons do Espírito Santo, distribuídos por sua vontade?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '5', 'Porque não foi aos anjos que sujeitou o mundo futuro, de que falamos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '6', 'Mas em certo lugar testificou alguém, dizendo: Que é o homem, para que dele te lembres? Ou o filho do homem, para que o visites?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '7', 'Tu o fizeste um pouco menor do que os anjos, de glória e de honra o coroaste, e o constituíste sobre as obras de tuas mãos:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '8', 'Todas as coisas lhe sujeitaste debaixo dos pés. Ora, visto que lhe sujeitou todas as coisas, nada deixou que lhe não esteja sujeito. Mas agora ainda não vemos que todas as coisas lhe estejam sujeitas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '9', 'Vemos, porém, coroado de glória e de honra aquele Jesus que fora feito um pouco menor do que os anjos, por causa da paixão da morte, para que, pela graça de Deus, provasse a morte por todos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '10', 'Porque convinha que aquele para quem são todas as coisas, e mediante quem tudo existe, trazendo muitos filhos à glória, consagrasse pelas aflições o príncipe da salvação deles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '11', 'Porque, assim o que santifica, como os que são santificados, são todos de um; por cuja causa não se envergonha de lhes chamar irmãos,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '12', 'Dizendo: Anunciarei o teu nome a meus irmãos, cantar-te-ei louvores no meio da congregação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '13', 'E outra vez: Porei nele a minha confiança. E outra vez: Eis-me aqui a mim, e aos filhos que Deus me deu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '14', 'E, visto como os filhos participam da carne e do sangue, também ele participou das mesmas coisas, para que pela morte aniquilasse o que tinha o império da morte, isto é, o diabo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '15', 'E livrasse todos os que, com medo da morte, estavam por toda a vida sujeitos à servidão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '16', 'Porque, na verdade, ele não tomou os anjos, mas tomou a descendência de Abraão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '17', 'Pelo que convinha que em tudo fosse semelhante aos irmãos, para ser misericordioso e fiel sumo sacerdote naquilo que é de Deus, para expiar os pecados do povo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '2', '18', 'Porque naquilo que ele mesmo, sendo tentado, padeceu, pode socorrer aos que são tentados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '1', 'PELO que, irmãos santos, participantes da vocação celestial, considerai a Jesus Cristo, apóstolo e sumo sacerdote da nossa confissão,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '2', 'Sendo fiel ao que o constituiu, como também o foi Moisés em toda a sua casa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '3', 'Porque ele é tido por digno de tanto maior glória do que Moisés, quanto maior honra do que a casa tem aquele que a edificou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '4', 'Porque toda a casa é edificada por alguém, mas o que edificou todas as coisas é Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '5', 'E, na verdade, Moisés foi fiel em toda a sua casa, como servo, para testemunho das coisas que se haviam de anunciar;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '6', 'Mas Cristo, como Filho sobre a sua própria casa; a qual casa somos nós, se tão somente conservarmos firme a confiança e a glória da esperança até ao fim.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '7', 'Portanto como diz o Espírito Santo, se ouvirdes hoje a sua voz,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '8', 'Não endureçais os vossos corações, como na provocação, no dia da tentação no deserto,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '9', 'Onde vossos pais me tentaram, me provocaram, e viram por quarenta anos as minhas obras.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '10', 'Por isso me indignei contra esta geração, e disse: Estes sempre erram em seu coração, e não conheceram os meus caminhos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '11', 'Assim jurei na minha ira que não entrarão no meu repouso.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '12', 'Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '13', 'Antes exortai-vos uns aos outros todos os dias, durante o tempo que se chama Hoje, para que nenhum de vós se endureça pelo engano do pecado;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '14', 'Porque nos tornamos participantes de Cristo, se retivermos firmemente o princípio da nossa confiança até ao fim.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '15', 'Enquanto se diz: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações, como na provocação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '16', 'Porque, havendo-a alguns ouvido, o provocaram; mas não todos os que saíram do Egipto por meio de Moisés.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '17', 'Mas com quem se indignou por quarenta anos? Não foi porventura com os que pecaram, cujos corpos caíram no deserto?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '18', 'E a quem jurou que não entrariam no seu repouso senão aos que foram desobedientes?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '3', '19', 'E vemos que não puderam entrar por causa da sua incredulidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '1', 'TEMAMOS pois que, porventura, deixada a promessa de entrar no seu repouso, pareça que algum de vós fica para trás.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '2', 'Porque também a nós foram pregadas as boas novas, como a eles, mas a palavra da pregação nada lhes aproveitou, porquanto não estava misturada com a fé naqueles que a ouviam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '3', 'Porque nós, os que temos crido, entramos no repouso, tal como disse: Assim jurei na minha ira que não entrarão no meu repouso; embora as suas obras estivessem acabadas desde a fundação do mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '4', 'Porque em certo lugar disse assim do dia sétimo: E repousou Deus de todas as suas obras no sétimo dia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '5', 'E outra vez neste lugar: Não entrarão no meu repouso.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '6', 'Visto, pois, que resta que alguns entrem nele, e que aqueles a quem primeiro foram pregadas as boas novas, não entraram por causa da desobediência,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '7', 'Determina outra vez um certo dia, Hoje, dizendo por David, muito tempo depois, como está dito: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '8', 'Porque, se Josué lhes houvesse dado repouso, não falaria depois de outro dia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '9', 'Portanto resta ainda um repouso para o povo de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '10', 'Porque aquele que entrou no seu repouso, ele próprio repousou de suas obras, como Deus das suas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '11', 'Procuremos pois entrar naquele repouso, para que ninguém caia no mesmo exemplo de desobediência.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '12', 'Porque a palavra de Deus é viva e eficaz e mais penetrante do que espada alguma de dois gumes, e penetra até a divisão da alma e do espírito, e das juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '13', 'E não há criatura alguma encoberta diante dele; antes todas as coisas estão nuas e patentes aos olhos daquele com quem temos de tratar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '14', 'Visto que temos um grande sumo sacerdote, Jesus, Filho de Deus, que penetrou nos céus, retenhamos firmemente a nossa confissão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '15', 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '4', '16', 'Cheguemos pois como confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '1', 'PORQUE todo o sumo sacerdote, tomado de entre os homens, é constituído a favor dos homens nas coisas concernentes a Deus, para que ofereça dons e sacrifícios pelos pecados;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '2', 'E possa compadecer-se ternamente dos ignorantes e errados; pois também ele mesmo está rodeado de fraqueza.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '3', 'E por esta causa deve ele, tanto pelo povo, como também por si mesmo, fazer oferta pelos pecados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '4', 'E ninguém toma para si esta honra, senão o que é chamado por Deus, como Aarão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '5', 'Assim também Cristo se não glorificou a si mesmo, para se fazer sumo sacerdote, mas aquele que lhe disse: Tu és meu Filho, hoje te gerei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '6', 'Como também diz noutro lugar: Tu és Sacerdote eternamente, segundo a ordem de Melquisedeque.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '7', 'O qual, nos dias da sua carne, oferecendo, com grande clamor e lágrimas, orações e súplicas ao que o podia livrar da morte, foi ouvido quanto ao que temia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '8', 'Ainda que era Filho, aprendeu a obediência, por aquilo que padeceu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '9', 'E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '10', 'Chamado por Deus sumo sacerdote, segundo a ordem de Melquisedeque.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '11', 'Do qual muito temos que dizer, de difícil interpretação; porquanto vos fizestes negligentes para ouvir,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '12', 'Porque, devendo já ser mestres pelo tempo, ainda necessitais de que se vos torne a ensinar quais sejam os primeiros rudimentos das palavras de Deus; e vos haveis feito tais que necessitais de leite, e não de sólido mantimento.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '13', 'Porque qualquer que ainda se alimenta de leite não está experimentado na palavra da justiça, porque é menino.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '5', '14', 'Mas o mantimento sólido é para os perfeitos, os quais, em razão do costume, têm os sentidos exercitados para discernir tanto o bem como o mal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '1', 'PELO que, deixando os rudimentos da doutrina de Cristo, prossigamos até à perfeição, não lançando de novo o fundamento do arrependimento das obras mortas e da fé em Deus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '2', 'E da doutrina dos baptismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '3', 'E isto faremos, se Deus o permitir.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '4', 'Porque é impossível que os que já uma vez foram iluminados, e provaram o dom celestial, e se fizeram participantes do Espírito Santo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '5', 'E provaram a boa palavra de Deus e as virtudes do século futuro,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '6', 'E recaíram, sejam outra vez renovados para arrependimento; pois assim quanto a eles, de novo crucificam o Filho de Deus, e o expõem ao vitupério.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '7', 'Porque a terra que embebe a chuva, que muitas vezes cai sobre ela, e produz erva proveitosa para aqueles por quem é lavrada, recebe a bênção de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '8', 'Mas a que produz espinhos e abrolhos, é reprovada, e perto está da maldição; o seu fim é ser queimada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '9', 'Mas de vós, ó amados, esperamos coisas melhores, e coisas que acompanham a salvação, ainda que assim falamos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '10', 'Porque Deus não é injusto para se esquecer da vossa obra, e do trabalho da caridade que para com o seu nome mostrastes, enquanto servistes aos santos; e ainda servis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '11', 'Mas desejamos que cada um de vós mostre o mesmo cuidado até ao fim, para completa certeza da esperança;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '12', 'Para que vos não façais negligentes, mas sejais imitadores dos que pela fé e paciência herdam as promessas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '13', 'Porque, quando Deus fez a promessa a Abraão, como não tinha outro maior por quem jurasse, jurou por si mesmo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '14', 'Dizendo: Certamente, abençoando, te abençoarei, e multiplicando te multiplicarei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '15', 'E assim esperando com paciência, alcançou a promessa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '16', 'Porque os homens certamente juram por alguém superior a eles, e o juramento para confirmação é, para eles, o fim de toda a contenda.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '17', 'Pelo que, querendo Deus mostrar mais abundantemente a imutabilidade do seu conselho aos herdeiros da promessa, se interpôs com juramento;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '18', 'Para que por duas coisas imutáveis, nas quais é impossível que Deus minta, tenhamos a firme consolação, nós, os que pomos o nosso refúgio em reter a esperança proposta;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '19', 'A qual temos como âncora da alma segura e firme, e que penetra até ao interior do véu,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '6', '20', 'Onde Jesus, nosso precursor, entrou por nós, feito eternamente sumo sacerdote, segundo a ordem de Melquisedeque.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '1', 'PORQUE este Melquisedeque, que era rei de Salém, sacerdote do Deus Altíssimo, e que saiu ao encontro de Abraão quando ele regressava da matança dos reis, e o abençoou,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '2', 'A quem também Abraão deu o dízimo de tudo, e primeiramente é, por interpretação, rei de justiça, e depois também rei de Salém, que é rei de paz;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '3', 'Sem pai, sem mãe, sem genealogia, não tendo princípio de dias nem fim de vida, mas sendo feito semelhante ao Filho de Deus, permanece sacerdote para sempre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '4', 'Considerai pois quão grande era este, a quem até o patriarca Abraão deu os dízimos dos despojos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '5', 'E os que de entre os filhos de Levi recebem o sacerdócio têm ordem, segundo a lei, de tomar o dízimo do povo, isto é, de seus irmãos, ainda que tenham saído dos lombos de Abraão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '6', 'Mas aquele cuja genealogia não é contada entre eles tomou dízimos de Abraão, e abençoou o que tinha as promessas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '7', 'Ora, sem contradição alguma, o menor é abençoado pelo maior.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '8', 'E aqui certamente tomam dízimos homens que morrem; ali, porém, aquele de quem se testifica que vive.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '9', 'E, para assim dizer, por meio de Abraão até Levi, que recebe dízimos, pagou dízimos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '10', 'Porque ainda ele estava nos lombos de seu pai quando Melquisedeque lhe saiu ao encontro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '11', 'De sorte que, se a perfeição fosse pelo sacerdócio levítico (porque sob ele o povo recebeu a lei), que necessidade havia logo de que outro sacerdote se levantasse, segundo a ordem de Melquisedeque, e não fosse chamado segundo a ordem de Aarão?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '12', 'Porque, mudando-se o sacerdócio, necessariamente se faz também mudança da lei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '13', 'Porque aquele de quem estas coisas se dizem pertence a outra tribo, da qual ninguém serviu ao altar,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '14', 'Visto ser manifesto que nosso SENHOR procedeu de Judá, e concernente a essa tribo nunca Moisés falou de sacerdócio.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '15', 'E muito mais manifesto é ainda, se à semelhança de Melquisedeque se levantar outro sacerdote,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '16', 'Que não foi feito segundo a lei do mandamento carnal, mas segundo a virtude da vida incorruptível.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '17', 'Porque dele assim se testifica: Tu és sacerdote eternamente, segundo a ordem de Melquisedeque.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '18', 'Porque o precedente mandamento é abrogado por causa da sua fraqueza e inutilidade');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '19', '(Pois a lei nenhuma coisa aperfeiçoou) e desta sorte é introduzida uma melhor esperança, pela qual chegamos a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '20', 'E visto como não é sem prestar juramento (porque certamente aqueles, sem juramento, foram feitos sacerdotes,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '21', 'Mas este com juramento por aquele que lhe disse: Jurou o SENHOR, e não se arrependerá; Tu és sacerdote eternamente segundo a ordem de Melquisedeque),');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '22', 'De tanto melhor concerto Jesus foi feito fiador.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '23', 'E, na verdade, aqueles foram feitos sacerdotes em grande número, porque pela morte foram impedidos de permanecer,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '24', 'Mas este, porque permanece eternamente, tem um sacerdócio perpétuo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '25', 'Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '26', 'Porque nos convinha tal sumo sacerdote, santo, inocente, imaculado, separado dos pecadores, e feito mais sublime do que os céus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '27', 'Que não necessitasse, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiramente por seus próprios pecados, e depois pelos do povo; porque isto fez ele, uma vez, oferecendo-se a si mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '7', '28', 'Porque a lei constitui sumos sacerdotes a homens fracos, mas a palavra do juramento, que veio depois da lei, constitui ao Filho, perfeito para sempre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '1', 'ORA a suma do que temos dito é que temos um sumo sacerdote tal, que está assentado nos céus à dextra do trono da majestade,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '2', 'Ministro do santuário, e do verdadeiro tabernáculo, o qual o SENHOR fundou, e não o homem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '3', 'Porque todo o sumo sacerdote é constituído para oferecer dons e sacrifícios; pelo que era necessário que este também tivesse alguma coisa que oferecer.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '4', 'Ora, se ele estivesse na terra, nem tão pouco sacerdote seria, havendo ainda sacerdotes que oferecem dons segundo a lei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '5', 'Os quais servem de exemplar e sombra das coisas celestiais; como Moisés divinamente foi avisado, estando já para acabar o tabernáculo; porque foi dito: Olha, faz tudo conforme o modelo que no monte se te mostrou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '6', 'Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador dum melhor concerto, que está confirmado em melhores promessas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '7', 'Porque, se aquele primeiro fora irrepreensível, nunca se teria buscado lugar para o segundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '8', 'Porque, repreendendo-os, lhes diz: Eis que virão dias, diz o SENHOR, em que com a casa de Israel e com a casa de Judá estabelecerei um novo concerto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '9', 'Não segundo o concerto que fiz com seus pais no dia em que os tomei pela mão, para os tirar da terra do Egipto; como não permaneceram naquele meu concerto, eu para eles não atentei, diz o SENHOR.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '10', 'Porque este é o concerto que depois daqueles dias farei com a casa de Israel, diz o SENHOR: Porei as minhas leis no seu entendimento, e em seu coração as escreverei; e eu lhes serei por Deus, e eles me serão por povo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '11', 'E não ensinará cada um a seu próximo, nem cada um ao seu irmão, dizendo: Conhece o SENHOR; porque todos me conhecerão, desde o menor deles até ao maior.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '12', 'Porque serei misericordioso para com suas iniquidades, e de seus pecados e de suas prevaricações não me lembrarei mais.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '8', '13', 'Dizendo Novo Concerto, envelheceu o primeiro. Ora, o que foi tornado velho, e se envelhece, perto está de acabar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '1', 'ORA também o primeiro tinha ordenanças de culto divino, e um santuário terrestre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '2', 'Porque um tabernáculo estava preparado, o primeiro, em que havia o candeeiro, e a mesa, e os pães da proposição; ao que se chama o santuário.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '3', 'Mas depois do segundo véu estava o tabernáculo que se chama o santo dos santos,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '4', 'Que tinha o incensário de ouro, e a arca do concerto, coberta de ouro toda em redor; em que estava um vaso de ouro, que continha o maná, e a vara de Aarão, que tinta florescido, e as tábuas do concerto;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '5', 'E sobre a arca os querubins da glória, que faziam sombra no propiciatório, das quais coisas não falaremos agora particularmente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '6', 'Ora, estando estas coisas assim preparadas, a todo o tempo entravam os sacerdotes no primeiro tabernáculo, cumprindo os serviços;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '7', 'Mas no segundo só o sumo sacerdote, uma vez no ano, não sem sangue, que oferecia por si mesmo e pelas culpas do povo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '8', 'Dando nisto a entender o Espírito Santo que ainda o caminho do santuário não estava descoberto enquanto se conservava em pé o primeiro tabernáculo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '9', 'Que é uma alegoria para o tempo presente, em que se oferecem dons e sacrifícios que, quanto à consciência, não podem aperfeiçoar aquele que faz o serviço;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '10', 'Consistindo somente em manjares, e bebidas, e várias abluções e justificações da carne, impostas até ao tempo da correcção.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '11', 'Mas, vindo Cristo, o sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '12', 'Nem por sangue de bodes e bezerros, mas por seu próprio sangue, entrou uma vez no santuário, havendo efectuado uma eterna redenção.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '13', 'Porque, se o sangue dos toiros e bodes, e a cinza duma novilha esparzida sobre os imundos, os santifica, quanto à purificação da carne,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '14', 'Quanto mais o sangue de Cristo, que pelo Espírito eterno se ofereceu a si mesmo imaculado a Deus, purificará as vossas consciências das obras mortas, para servirdes ao Deus vivo?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '15', 'E por isso é Mediador dum novo Testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '16', 'Porque onde há testamento necessário é que intervenha a morte do testador.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '17', 'Porque um testamento tem força onde houve morte; ou terá ele algum valor enquanto o testador vive?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '18', 'Pelo que também o primeiro não foi consagrado sem sangue;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '19', 'Porque, havendo Moisés anunciado a todo o povo todos os mandamentos segundo a lei, tomou o sangue dos bezerros e dos bodes, com água, lã purpúrea e hissope, e aspergiu tanto o mesmo livro como todo o povo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '20', 'Dizendo: Este é o sangue do testamento que Deus vos tem mandado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '21', 'E semelhantemente aspergiu com sangue o tabernáculo e todos os vasos do ministério.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '22', 'E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '23', 'De sorte que era bem necessário que as figuras das coisas que estão no céu assim se purificassem; mas as próprias coisas celestiais com sacrifícios melhores do que estes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '24', 'Porque Cristo não entrou num santuário feito por mãos, figura do verdadeiro, porém no mesmo céu, para agora comparecer por nós perante a face de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '25', 'Nem também para a si mesmo se oferecer muitas vezes, como o sumo sacerdote cada ano entra no santuário com sangue alheio;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '26', 'Doutra maneira, necessário lhe fora padecer muitas vezes desde a fundação do mundo; mas agora na consumação dos séculos uma vez se manifestou, para aniquilar o pecado pelo sacrifício de si mesmo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '27', 'E, como aos homens está ordenado morrerem uma vez, vindo depois disso o juízo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '9', '28', 'Assim também Cristo, oferecendo-se uma vez para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para salvação.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '1', 'PORQUE, tendo a lei a sombra dos bens futuros, e não a imagem exacta das coisas, nunca, pelos mesmos sacrifícios que continuamente se oferecem cada ano, pode aperfeiçoar os que a eles se chegam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '2', 'Doutra maneira, teriam deixado de se oferecer, porque, purificados uma vez os ministrantes, nunca mais teriam consciência de pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '3', 'Nesses sacrifícios, porém, cada ano se faz comemoração dos pecados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '4', 'Porque é impossível que o sangue dos toiros e dos bodes tire os pecados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '5', 'Pelo que, entrando no mundo, diz: Sacrifício e oferta não quiseste, mas corpo me preparaste;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '6', 'Holocaustos e oblações pelo pecado não te agradaram.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '7', 'Então disse: Eis aqui venho (no princípio do livro está escrito de mim), para fazer, ó Deus, a tua vontade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '8', 'Como acima diz: Sacrifício e oferta, e holocaustos e oblações pelo pecado não quiseste, nem te agradaram (os quais se oferecem segundo a lei).');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '9', 'Então disse: Eis aqui venho, para fazer, ó Deus, a tua vontade. Tira o primeiro, para estabelecer o segundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '10', 'Na qual vontade temos sido santificados pela oblação do corpo de Jesus Cristo, feita uma vez.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '11', 'E assim todo o sacerdote aparece cada dia, ministrando e oferecendo muitas vezes os mesmos sacrifícios, que nunca podem tirar os pecados;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '12', 'Mas este havendo oferecido um único sacrifício pelos pecados, está assentado para sempre à dextra de Deus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '13', 'Daqui em diante esperando até que os seus inimigos sejam postos por escabelo de seus pés.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '14', 'Porque com uma só oblação aperfeiçoou para sempre os que são santificados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '15', 'E também o Espírito Santo no-lo testifica, porque depois de haver dito:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '16', 'Este é o concerto que farei com eles depois daqueles dias, diz o SENHOR: Porei as minhas leis em seus corações, e as escreverei em seus entendimentos; acrescenta:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '17', 'E jamais me lembrarei dos seus pecados e das suas iniquidades.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '18', 'Ora, onde há remissão destes, não há mais oblação pelo pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '19', 'Tendo pois, irmãos, ousadia para entrar no santuário, pelo sangue de Jesus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '20', 'Pelo novo e vivo caminho que ele nos consagrou, pelo véu, isto é, pela sua carne,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '21', 'E tendo um grande sacerdote sobre a casa de Deus,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '22', 'Cheguemo-nos com verdadeiro coração, em inteira certeza de fé; tendo os corações purificados da má consciência, e o corpo lavado com água limpa,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '23', 'Retenhamos firmes a confissão da nossa esperança; porque fiel é o que prometeu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '24', 'E consideremo-nos uns aos outros, para nos estimularmos à caridade e às boas obras:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '25', 'Não deixando a nossa congregação, como é costume de alguns, antes admoestando-nos uns aos outros; e tanto mais, quanto vedes que se vai aproximando aquele dia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '26', 'Porque, se pecarmos voluntariamente, depois de termos recebido o conhecimento da verdade, já não resta mais sacrifício pelos pecados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '27', 'Mas uma certa expectação horrível do juízo, e ardor de fogo, que há de devorar os adversários.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '28', 'Quebrantando alguém a lei de Moisés, morre sem misericórdia, só pela palavra de duas ou três testemunhas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '29', 'De quanto maior castigo cuidais vós será julgado merecedor aquele que pisar o Filho de Deus, e tiver por profano o sangue do testamento, com que foi santificado, e fizer agravo ao Espírito da graça?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '30', 'Porque bem conhecemos aquele que disse: Minha é a vingança, eu darei a recompensa, diz o SENHOR. E outra vez: O SENHOR julgará o seu povo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '31', 'Horrenda coisa é cair nas mãos do Deus vivo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '32', 'Lembrai-vos, porém, dos dias passados, em que, depois de serdes iluminados, suportastes grande combate de aflições.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '33', 'Em parte fostes feitos espectáculo com vitupérios e tribulações, e em parte fostes participantes com os que assim foram tratados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '34', 'Porque também vos compadecestes dos que estavam nas prisões, e com gozo permitistes a espoliação dos vossos bens, sabendo que em vós mesmos tendes nos céus uma possessão melhor e permanente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '35', 'Não rejeiteis pois a vossa confiança, que tem grande e avultado galardão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '36', 'Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '37', 'Porque ainda um poucochinho de tempo, e o que há de vir virá, e não tardará.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '38', 'Mas o justo viverá da fé; e, se ele recuar, a minha alma não tem prazer nele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '10', '39', 'Nós, porém, não somos daqueles que se retiram para a perdição, mas daqueles que crêem para a conservação da alma.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '1', 'ORA, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não vêem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '2', 'Porque por ela os antigos alcançaram testemunho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '3', 'Pela fé entendemos que os mundos pela palavra de Deus foram criados; de maneira que aquilo que se vê não foi feito do que é aparente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '4', 'Pela fé Abel ofereceu a Deus maior sacrifício do que Caim, pelo qual alcançou testemunho de que era justo, dando Deus testemunho dos seus dons, e por ela, depois de morto, ainda fala.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '5', 'Pela fé Enoque foi trasladado para não ver a morte, e não foi achado, porque Deus o trasladara; visto como antes da sua trasladação alcançou testemunho de que agradara a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '6', 'Ora, sem fé é impossível agradar-lhe porque é necessário que aquele que se aproxima de Deus creia que ele existe, e que é galardoador dos que o buscam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '7', 'Pela fé Noé, divinamente avisado das coisas que ainda se não viam, temeu, e, para salvação da sua família, preparou a arca, pela qual condenou o mundo; e foi feito herdeiro da justiça que é segundo a fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '8', 'Pela fé Abraão, sendo chamado, obedeceu, indo para um lugar que havia de receber por herança; e saiu sem saber para onde ia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '9', 'Pela fé habitou na terra da promessa, como em terra alheia, morando em cabanas com Isaque e Jacob, herdeiros com ele da mesma promessa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '10', 'Porque esperava a cidade que tem fundamento, da qual o artífice e construtor é Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '11', 'Pela fé também a mesma Sara recebeu a virtude de conceber, e deu à luz já fora da idade; porquanto teve por fiel aquele que lho tinha prometido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '12', 'Pelo que também de um, e esse já amortecido, descenderam tantos, em multidão, como as estrelas do céu e como a areia inumerável que está na praia do mar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '13', 'Todos estes morreram na fé, sem terem recebido as promessas; mas vendo-as de longe, e crendo-as e abraçando-as, confessaram que eram estrangeiros e peregrinos na terra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '14', 'Porque, os que isto dizem, claramente mostram que buscam uma pátria.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '15', 'E se, na verdade, se lembrassem daquela donde haviam saído, teriam oportunidade de tornar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '16', 'Mas agora desejam uma melhor, isto é, a celestial. Pelo que também Deus se não envergonha deles, de se chamar seu Deus, porque já lhes preparou uma cidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '17', 'Pela fé ofereceu Abraão a Isaque, quando foi provado; sim, aquele que recebera as promessas ofereceu o seu unigénito.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '18', 'Sendo-lhe dito: Em Isaque será chamada a tua descendência, considerou que Deus era poderoso para até dos mortos o ressuscitar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '19', 'E daí também em figura ele o recobrou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '20', 'Pela fé Isaque abençoou Jacob e Esaú, no tocante às coisas futuras.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '21', 'Pela fé Jacob, próximo da morte abençoou cada um dos filhos de José, e adorou encostado à ponta do seu bordão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '22', 'Pela fé José, próximo da morte, fez menção da saída dos filhos de Israel, e deu ordem acerca de seus ossos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '23', 'Pela fé Moisés, já nascido, foi escondido três meses por seus pais, porque viram que era um menino formoso; e não temeram o mandamento do rei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '24', 'Pela fé Moisés, sendo já grande recusou ser chamado filho da filha de Faraó,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '25', 'Escolhendo antes ser maltratado com o povo de Deus do que por um pouco de tempo ter o gozo do pecado;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '26', 'Tendo por maiores riquezas o vitupério de Cristo do que os tesouros do Egipto; porque tinha em vista a recompensa.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '27', 'Pela fé deixou o Egipto, não temendo a ira do rei; porque ficou firme, como vendo o invisível.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '28', 'Pela fé celebrou a páscoa e a aspersão do sangue, para que o destruidor dos primogénitos lhes não tocasse.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '29', 'Pela fé passaram o Mar Vermelho, como por terra seca; o que intentando os egípcios, se afogaram.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '30', 'Pela fé caíram os muros de Jericó, sendo rodeados durante sete dias.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '31', 'Pela fé Raabe, a meretriz, não pereceu com os incrédulos, acolhendo em paz os espias.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '32', 'E que mais direi? Faltar-me-ia o tempo contando de Gideão, e de Baraque, de Sansão, e de Jefté, e de David, e de Samuel e dos profetas;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '33', 'Os quais pela fé venceram reinos, praticaram a justiça, alcançaram promessas, fecharam as bocas dos leões.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '34', 'Apagaram a força do fogo, escaparam do fio da espada, da fraqueza tiraram forças, na batalha se esforçaram, puseram em fugida os exércitos dos estranhos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '35', 'As mulheres receberam pela ressurreição os seus mortos; uns foram torturados, não aceitando o seu livramento, para alcançarem uma melhor ressurreição;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '36', 'E outros experimentaram escárnio e açoites, e até cadeias e prisões.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '37', 'Foram apedrejados, serrados, tentados, mortos ao fio da espada; andaram vestidos de peles de ovelhas e de cabras, desamparados, aflitos e maltratados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '38', '(Dos quais o mundo não era digno), errantes pelos desertos, e montes, e pelas covas e cavernas da terra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '39', 'E todos estes, tendo tido testemunho pela fé, não alcançaram a promessa,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '11', '40', 'Provendo Deus alguma coisa melhor a nosso respeito, para que eles sem nós não fossem aperfeiçoados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '1', 'PORTANTO nós também, pois que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo o embaraço, e o pecado que tão de perto nos rodeia, e corramos com paciência a carreira que nos está proposta,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '2', 'Olhando para Jesus, autor e consumador da fé, o qual pelo gozo que lhe estava proposto suportou a cruz, desprezando a afronta; e assentou-se à dextra do trono de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '3', 'Considerai pois aquele que suportou tais contradições dos pecadores contra si mesmo, para que não enfraqueçais, desfalecendo em vossos ânimos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '4', 'Ainda não resististes até ao sangue, combatendo contra o pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '5', 'E já vos esquecestes da exortação que argumenta convosco como filhos: Filho meu, não desprezes a correcção do SENHOR, e não desmaies quando por ele fores repreendido;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '6', 'Porque o SENHOR corrige o que ama, e açoita a qualquer que recebe por filho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '7', 'Se suportais a correcção, Deus vos trata como filhos; porque, que filho há a quem o pai não corrija?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '8', 'Mas, se estais sem disciplina, da qual todos são feitos participantes, sois então bastardos, e não filhos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '9', 'Além do que tivemos nossos pais segundo a, carne, para nos corrigirem, e nós os reverenciámos: não nos sujeitaremos muito mais ao Pai dos espíritos, para vivermos?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '10', 'Porque aqueles, na verdade, por um pouco de tempo, nos corrigiam como bem lhes parecia; mas este, para nosso proveito, para sermos participantes da sua santidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '11', 'E, na verdade, toda a correcção, ao presente, não parece ser de gozo, senão de tristeza, mas depois produz um fruto pacífico de justiça nos exercitados por ela.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '12', 'Portanto tornai a levantar as mãos cansadas, e os joelhos desconjuntados,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '13', 'E fazei veredas direitas para os vossos pés, para que o que manqueja se não desvie inteiramente, antes seja sarado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '14', 'Segui a paz com todos e a santificação, sem a qual ninguém verá o SENHOR;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '15', 'Tendo cuidado de que ninguém se prive da graça de Deus, e de que nenhuma raiz de amargura, brotando vos perturbe, e por ela muitos se contaminem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '16', 'E ninguém seja devasso, ou profano, como Esaú, que por um manjar vendeu o seu direito de primogenitura.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '17', 'Porque bem sabeis que, querendo ele ainda depois herdar a bênção, foi rejeitado, porque não achou lugar de arrependimento, ainda que com lágrimas o buscou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '18', 'Porque não chegastes ao monte palpável, aceso em fogo, e à escuridão, e às trevas, e à tempestade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '19', 'E ao sonido da trombeta, e à voz das palavras, a qual os que a ouviram pediram que se lhes não falasse mais;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '20', 'Porque não podiam suportar o que se lhes mandava: se até um animal tocar o monte, será apedrejado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '21', 'E tão terrível era a visão, que Moisés disse: Estou todo assombrado, e tremendo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '22', 'Mas chegastes ao monte de Sião, e à cidade do Deus vivo, à Jerusalém celestial, e aos muitos milhares de anjos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '23', 'À universal assembleia e igreja dos primogénitos, que estão inscritos nos céus, e a Deus, o juiz de todos, e aos espíritos dos justos aperfeiçoados;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '24', 'E a Jesus, o Mediador duma Nova Aliança, e ao sangue da aspersão que fala melhor do que o de Abel.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '25', 'Vede que não rejeiteis ao que fala; porque, se não escaparam aqueles que rejeitaram o que na terra os advertia, muito menos nós, se nos desviarmos daquele que é dos céus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '26', 'A voz do qual moveu então a terra, mas agora anunciou, dizendo: Ainda uma vez comoverei, não só a terra, senão também o céu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '27', 'E esta palavra: Ainda uma vez, mostra a mudança das coisas móveis, como coisas feitas, para que as imóveis permaneçam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '28', 'Pelo que, tendo recebido um reino que não pode ser abalado retenhamos a graça, pela qual sirvamos a Deus agradavelmente com reverência e piedade;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '12', '29', 'Porque o nosso Deus é um fogo consumidor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '1', 'PERMANEÇA a caridade fraternal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '2', 'Não vos esqueçais da hospitalidade, porque por ela alguns, não o sabendo hospedaram anjos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '3', 'Lembrai-vos dos presos, como se estivésseis presos com eles, e dos maltratados, como sendo-o vós mesmos também no corpo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '4', 'Venerado seja entre todos o matrimónio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '5', 'Sejam vossos costumes sem avareza contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '6', 'E assim com confiança ousemos dizer: O SENHOR é o meu ajudador, e não temerei o que me possa fazer o homem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '7', 'Lembrai-vos dos vossos pastores, que vos falaram a palavra de Deus, a fé dos quais imitai, atentando para a sua maneira de viver.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '8', 'Jesus Cristo é o mesmo ontem, e hoje, e eternamente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '9', 'Não vos deixeis levar em redor por doutrinas várias e estranhas porque bom é que o coração se fortifique com graça, e não com manjares, que de nada aproveitaram aos que a eles se entregaram.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '10', 'Temos um altar, de que não têm direito de comer os que servem ao tabernáculo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '11', 'Porque os corpos dos animais, cujo sangue é, pelo pecado, trazido pelo sumo sacerdote para o santuário, são queimados fora do arraial.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '12', 'E por isso também Jesus, para santificar o povo pelo seu próprio sangue, padeceu fora da porta.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '13', 'Saiamos pois a ele fora do arraial, levando o seu vitupério.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '14', 'Porque não temos aqui cidade permanente, mas buscamos a futura.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '15', 'Portanto ofereçamos sempre por ele a Deus sacrifício de louvor, isto é, o fruto dos lábios que confessam o seu nome.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '16', 'E não vos esqueçais da beneficência e comunicação, porque com tais sacrifícios Deus se agrada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '17', 'Obedecei a vossos pastores, e sujeitai-vos a eles; porque velam por vossas almas, como aqueles que hão de dar conta delas; para que o façam com alegria e não gemendo, porque isso não vos seria útil.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '18', 'Orai por nós, porque confiamos que, temos boa consciência, como aqueles que em tudo querem portar-se honestamente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '19', 'E rogo-vos com instância que assim o façais, para que eu mais depressa vos seja restituído.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '20', 'Ora o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso SENHOR Jesus Cristo, Grande Pastor das ovelhas,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '21', 'Vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '22', 'Rogo-vos, porém, irmãos, que suporteis a palavra desta exortação; porque abreviadamente vos escrevi.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '23', 'Sabei que já está solto o irmão Timóteo, com o qual (se vier depressa) vos verei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '24', 'Saudai a todos os vossos chefes e a todos os santos. Os de Itália vos saúdam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('58', '13', '25', 'A graça seja com todos vós. Ámen.');