INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '1', '¶ PEDRO, apóstolo de Jesus Cristo, aos estrangeiros dispersos no Ponto, Galácia, Capadócia, Ásia e Bitínia;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '2', 'Eleitos segundo a presciência de Deus Pai, em santificação do Espírito, para a obediência e aspersão do sangue de Jesus Cristo: graça e paz vos sejam multiplicadas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '3', 'Bendito seja o Deus e Pai de nosso SENHOR Jesus Cristo, que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo de entre os mortos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '4', 'Para uma herança incorruptível, incontaminável, e que se não pode murchar, guardada nos céus para vós,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '5', 'Que mediante a fé estais guardados na virtude de Deus para a salvação, já prestes para se revelar no último tempo,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '6', 'Em que vós grandemente vos alegrais, ainda que agora importa, sendo necessário, que estejais por um pouco contristados com várias tentações.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '7', 'Para que a prova da vossa fé, muito mais preciosa do que o ouro que perece e é provado pelo fogo, se ache em louvor, e honra, e glória, na revelação de Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '8', 'Ao qual, não o havendo visto, amais; no qual, não o vendo agora, mas crendo, vos alegrais com gozo inefável e glorioso;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '9', 'Alcançando o fim da vossa fé, a salvação das almas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '10', 'Da qual salvação inquiriram e trataram diligentemente os profetas que profetizaram da graça que vos foi dada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '11', 'Indagando que tempo ou que ocasião de tempo o Espírito de Cristo, que estava neles indicava, anteriormente testificando os sofrimentos que a Cristo haviam de vir, e a glória que se lhes havia de seguir.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '12', 'Aos quais foi revelado que, não para si mesmos, mas para nós, eles ministravam estas coisas que agora vos foram anunciadas por aqueles que, pelo Espírito Santo enviado do céu, vos pregaram o evangelho; para as quais coisas os anjos desejam bem atentar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '13', 'Portanto, cingindo os lombos do vosso entendimento, sede sóbrios, e esperai inteiramente na graça que se vos ofereceu na revelação de Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '14', 'Como filhos obedientes, não vos conformando com as concupiscências que antes havia em vossa ignorância.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '15', 'Mas, como é santo aquele que vos chamou, sede vós também santos em toda a vossa maneira de viver;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '16', 'Porquanto escrito está: Sede santos, porque eu sou santo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '17', 'E, se invocais por Pai aquele que, sem acepção de pessoas, julga segundo a obra de cada um, andai em temor, durante o tempo da vossa peregrinação;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '18', 'Sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver que por tradição recebestes dos vossos pais,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '19', 'Mas com o precioso sangue de Cristo, como de um cordeiro imaculado e incontaminado,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '20', 'O qual, na verdade, em outro tempo foi conhecido, ainda antes da fundação do mundo, mas manifestado nestes últimos tempos por amor de vós;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '21', 'E por ele credes em Deus, que o ressuscitou dos mortos, e lhe deu glória, para que a vossa fé e esperança estivessem em Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '22', 'Purificando as vossas almas na obediência à verdade, para a caridade fraternal, não fingida; amai-vos ardentemente uns aos outros com um coração puro;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '23', 'Sendo de novo gerados, não de semente corruptível, mas da incorruptível, pela palavra de Deus, viva, e que permanece para sempre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '24', 'Porque toda a carne é como a erva, e toda a flor da erva. Secou-se a erva, e caiu a sua flor;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '1', '25', 'Mas a palavra do SENHOR permanece para sempre; e esta é a palavra que entre vós foi evangelizada.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '1', 'DEIXANDO pois toda a malícia, e todo o engano, e fingimentos, e invejas, e todas as murmurações,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '2', 'Desejai afectuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que por ele vades crescendo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '3', 'Se é que provastes que o SENHOR é benigno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '4', 'Chegando-vos para ele - pedra viva, reprovada, na verdade, pelos homens, mas para com Deus eleita e preciosa,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '5', 'Vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '6', 'Pelo que também na Escritura se contém: Eis que ponho em Sião a pedra principal da esquina, eleita e preciosa; e quem nela crer não será confundido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '7', 'E assim para vós, os que credes, é preciosa, mas, para os rebeldes, a pedra que os edificadores reprovaram essa foi a principal da esquina;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '8', 'E uma pedra de tropeço e rocha de escândalo, para aqueles que tropeçam na palavra, sendo desobedientes; para o que também foram destinados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '9', 'Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '10', 'Vós, que em outro tempo não éreis povo, mas agora sois povo de Deus; que não tínheis alcançado misericórdia, mas agora alcançastes misericórdia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '11', 'Amados, peço-vos, como a peregrinos e forasteiros, que vos abstenhais das concupiscências que combatem contra a alma;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '12', 'Tendo o vosso viver honesto entre os gentios; para que, naquilo em que falam mal de vós, como de malfeitores, glorifiquem a Deus no dia da visitação, pelas boas obras que em vós observem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '13', 'Sujeitai-vos pois a toda a ordenação humana por amor do SENHOR: quer ao rei, como superior;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '14', 'Quer aos governadores, como por ele enviados para castigo dos malfeitores, e para louvor dos que fazem o bem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '15', 'Porque assim é a vontade de Deus, que, fazendo bem, tapeis a boca à ignorância dos homens loucos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '16', 'Como livres, e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '17', 'Honrai a todos. Amai a fraternidade. Temei a Deus. Honrai o rei.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '18', 'Vós, servos, sujeitai-vos com todo o temor aos senhores, não somente aos bons e humanos, mas também aos maus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '19', 'Porque é coisa agradável, que alguém, por causa da consciência para com Deus, sofra agravos, padecendo injustamente.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '20', 'Porque, que glória será essa, se, pecando, sois esbofeteados e sofreis? Mas se, fazendo bem, sois afligidos, e o sofreis, isso é agradável a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '21', 'Porque para isto sois chamados; pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '22', 'O qual não cometeu pecado, nem na sua boca se achou engano.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '23', 'O qual, quando o injuriavam, não injuriava, e quando padecia não ameaçava, mas entregava-se aquele que julga justamente:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '24', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '2', '25', 'Porque éreis como ovelhas desgarradas: mas agora tendes voltado ao Pastor e Bispo das vossas almas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '1', 'SEMELHANTEMENTE vós, mulheres, sede sujeitas aos vossos próprios maridos; para que também, se alguns não obedecem à palavra, pelo porte de suas mulheres sejam ganhos sem palavra;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '2', 'Considerando a vossa vida casta, em temor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '3', 'O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de jóias de ouro, na compostura dos vestidos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '4', 'Mas o homem encoberto no coração; no incorruptível trajo de um espírito manso e quieto, que é precioso diante de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '5', 'Porque assim se adornavam também antigamente as santas mulheres que esperavam em Deus, e estavam sujeitas aos seus próprios maridos;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '6', 'Como Sara obedecia a Abraão, chamando-lhe senhor; da qual vós sois filhos, fazendo o bem, e não temendo nenhum espanto.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '7', 'Igualmente vós, maridos, coabitai com elas com entendimento, dando honra à mulher, como vaso mais fraco; para que não sejam impedidas as vossas orações.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '8', 'E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '9', 'Não tornando mal por mal, ou injúria; antes, pelo contrário, bendizendo: sabendo que para isto fostes chamados, para que por herança alcanceis a bênção.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '10', 'Porque quem quer amar a vida, e ver os dias bons, refreie a sua língua do mal, e os seus lábios não falem engano.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '11', 'Aparte-se do mal, e faça o bem; busque a paz, e siga-a.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '12', 'Porque os olhos do SENHOR estão sobre os justos, e os seus ouvidos atentos às suas orações; mas o rosto do SENHOR é contra os que fazem males.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '13', 'E qual é aquele que vos fará mal, se fordes zelosos do bem?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '14', 'Mas também se padecerdes por amor da justiça, sois bem-aventurados. E não temais com medo deles, nem vos turbeis;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '15', 'Antes santificai a Cristo, como SENHOR, em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '16', 'Tendo uma boa consciência, para que, naquilo em que falam mal de vós, como de malfeitores, fiquem confundidos os que blasfemam do vosso bom porte em Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '17', 'Porque melhor é que padeçais fazendo bem (se a vontade de Deus assim o quer), do que fazendo mal.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '18', 'Porque também Cristo padeceu uma vez pelos pecados, o justo pelos injustos, para levar-nos a Deus; mortificado, na verdade, na carne, mas vivificado pelo Espírito;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '19', 'No qual também foi, e pregou aos espíritos em prisão;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '20', 'Os quais noutro tempo foram rebeldes, quando a longanimidade de Deus esperava nos dias de Noé, enquanto se preparava a arca; na qual poucas (isto é oito) almas se salvaram pela água;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '21', 'Que também, como uma verdadeira figura, agora vos salva, baptismo, não do despojamento da imundície da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '3', '22', 'O qual está à dextra de Deus, tendo subido ao céu, havendo-se-lhe sujeitado os anjos, e as autoridades, e as potências.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '1', 'ORA pois, já que Cristo padeceu por nós na carne, armai-vos também vós com este pensamento, que aquele que padeceu na carne já cessou do pecado;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '2', 'Para que, no tempo que vos resta na carne, não vivais mais segundo as concupiscências dos homens, mas segundo a vontade de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '3', 'Porque é bastante que no tempo passado da vida fizéssemos a vontade dos gentios, andando em dissoluções, concupiscências, borrachices, glutonarias, bebedices e abomináveis idolatrias;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '4', 'E acham estranho não correrdes com eles no mesmo desenfreamento de dissolução, blasfemando de vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '5', 'Os quais hão de dar conta ao que está preparado para julgar os vivos e os mortos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '6', 'Porque por isto foi pregado o evangelho também aos mortos, para que, na verdade, fossem julgados segundo os homens na carne, mas vivessem segundo Deus em espírito;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '7', 'E já está próximo o fim de todas as coisas; portanto sede sóbrios e vigiai em oração.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '8', 'Mas, sobretudo, tende ardente caridade uns para com os outros; porque a caridade cobrirá a multidão dos pecados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '9', 'Sendo hospitaleiros uns para com os outros, sem murmurações.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '10', 'Cada um administre aos outros o dom como o recebeu, como bons dispenseiros da multiforme graça de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '11', 'Se alguém falar, fale segundo as palavras de Deus: se alguém administrar, administre segundo o poder que Deus dá; para que em tudo Deus seja glorificado por Jesus Cristo, a quem pertence a glória e poder para todo o sempre. Ámen.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '12', 'Amados, não estranheis a ardente prova que vem sobre vós para vos tentar, como se coisa estranha vos acontecesse;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '13', 'Mas alegrai-vos no facto de serdes participantes das aflições de Cristo, para que também na revelação da sua glória vos regozijeis e alegreis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '14', 'Se pelo nome de Cristo sois vituperados, bem-aventurados sois, porque sobre vós repousa o Espírito da glória de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '15', 'Que nenhum de vós padeça como homicida, ou ladrão, ou malfeitor, ou como o que se entremete em negócios alheios;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '16', 'Mas, se padece como cristão, não se envergonhe, antes glorifique a Deus nesta parte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '17', 'Porque já é tempo que comece o julgamento pela casa de Deus; e, se primeiro começa por nós, qual será o fim daqueles que são desobedientes ao evangelho de Deus?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '18', 'E, se o justo apenas se salva, onde aparecerá o ímpio e o pecador?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '4', '19', 'Portanto também os que padecem segundo a vontade de Deus encomendem-lhe as suas almas, como ao fiel Criador, fazendo o bem.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '1', 'AOS presbíteros, que estão entre vós, admoesto eu, que sou também presbítero com eles; testemunha das aflições de Cristo, e participante da glória que se há de revelar:');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '2', 'Apascentai o rebanho de Deus, que está entre vós, tendo cuidado dele, não por força, mas voluntariamente; nem por torpe ganância, mas de ânimo pronto;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '3', 'Nem como tendo domínio sobre a herança de Deus, mas servindo de exemplo ao rebanho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '4', 'E, quando aparecer o Sumo Pastor, alcançareis a incorruptível coroa de glória.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '5', 'Semelhantemente vós, mancebos, sede sujeitos aos anciãos; e sede todos sujeitos uns aos outros, e revesti-vos de humildade, porque Deus resiste aos soberbos, mas dá graça aos humildes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '6', 'Humilhai-vos pois debaixo da potente mão de Deus, para que a seu tempo vos exalte;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '7', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '8', 'Sede sóbrios; vigiai; porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '9', 'Ao qual resisti firmes na fé: sabendo que as mesmas aflições se cumprem entre os vossos irmãos no mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '10', 'E o Deus de toda a graça, que em Cristo Jesus vos chamou à sua eterna glória, depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará e fortalecerá.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '11', 'A ele seja a glória e o poderio para todo o sempre. Ámen');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '12', 'Por Silvano, vosso fiel irmão, como cuido, escrevi abreviando e testificando que esta é a verdadeira graça de Deus, na qual estais firmes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '13', 'A vossa co-eleita em Babilónia vos saúda e meu filho Marcos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('60', '5', '14', 'Saudai-vos uns aos outros com ósculo de amor. Paz seja com todos vós que estais em Cristo Jesus. Ámen.');