INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '1', '¶ O QUE era desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que temos contemplado, e as nossas mãos tocaram, da Palavra da vida,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '2', '(Porque a vida foi manifestada, e nós a vimos, e testificamos dela, e vos anunciamos a vida eterna, que estava com o Pai, e nos foi manifestada):');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '3', 'O que vimos e ouvimos, isso vos anunciamos, para que também tenhais comunhão connosco; e a nossa comunhão é com o Pai, e com seu Filho Jesus Cristo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '4', 'Estas coisas vos escrevemos, para que o vosso gozo se cumpra.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '5', 'E esta é a mensagem que dele ouvimos, e vos anunciamos: que Deus é luz, e não há nele trevas nenhumas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '6', 'Se dissermos que temos comunhão com ele, e andarmos em trevas, mentimos, e não praticamos a verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '7', 'Mas se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo o pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '8', 'Se dissermos que não temos pecado, enganamo-nos a nós mesmos, e não há verdade em nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '9', 'Se confessarmos os nossos pecados, ele é fiel e justo, para nos perdoar os pecados, e nos purificar de toda a injustiça.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '1', '10', 'Se dissermos que não pecámos, fazemo-lo mentiroso, e a sua palavra não está em nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '1', 'MEUS filhinhos, estas coisas vos escrevo, para que não pequeis; e, se alguém pecar, temos um Advogado para com o Pai, Jesus Cristo, o justo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '2', 'E ele é a propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos de todo o mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '3', 'E nisto sabemos que o conhecemos: se guardamos os seus mandamentos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '4', 'Aquele que diz: Eu conheço-o, e não guarda os seus mandamentos, é mentiroso, e nele não está a verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '5', 'Mas qualquer que guarda a sua palavra, o amor de Deus está nele verdadeiramente aperfeiçoado: nisto conhecemos que estamos nele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '6', 'Aquele que diz que está nele, também deve andar como ele andou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '7', 'Irmãos, não vos escrevo mandamento novo, mas o mandamento antigo, que desde o princípio tivestes. Este mandamento antigo é a palavra que desde o princípio ouvistes.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '8', 'Outra vez vos escrevo um mandamento novo, que é verdadeiro nele e em vós; porque vão passando as trevas, e já a verdadeira luz alumia.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '9', 'Aquele que diz que está na luz, e aborrece a seu irmão, até agora está em trevas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '10', 'Aquele que ama a seu irmão está na luz, e nele não há escândalo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '11', 'Mas aquele que aborrece a seu irmão está em trevas, e anda em trevas, e não sabe para onde deva ir; porque as trevas lhe cegaram os olhos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '12', 'Filhinhos, escrevo-vos, porque pelo seu nome vos são perdoados os pecados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '13', 'Pais, escrevo-vos, porque conhecestes aquele que é desde o princípio. Mancebos, escrevo-vos, porque vencestes o maligno. Eu vos escrevi, filhos, porque conhecestes o Pai.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '14', 'Eu vos escrevi, pais, porque já conhecestes aquele que é desde o princípio. Eu vos escrevi, mancebos, porque sois fortes, e a palavra de Deus está em vós, e já vencestes o maligno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '15', 'Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '16', 'Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a sabedoria da vida não é do Pai, mas do mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '17', 'E o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '18', 'Filhinhos, é já a última hora; e, como ouvistes que vem o anti-cristo, também agora muitos se têm feito anti-cristos: por onde conhecemos que é já a última hora.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '19', 'Saíram de nós, mas não eram de nós; porque, se fossem de nós, ficariam connosco: mas isto é para que se manifestasse que não são todos de nós.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '20', 'E vós tendes a unção do Santo, e sabeis tudo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '21', 'Não vos escrevi porque não soubésseis a verdade, mas porque a sabeis, e porque nenhuma mentira vem da verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '22', 'Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? É o anti-cristo esse mesmo que nega o Pai e o Filho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '23', 'Qualquer que nega o Filho, também não tem o Pai; e aquele que confessa o Filho, tem também o Pai.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '24', 'Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '25', 'E esta é a promessa que ele nos fez: a vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '26', 'Estas coisas vos escrevi acerca dos que vos enganam.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '27', 'E a unção, que vós recebestes dele, fica em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina todas os coisas, e é verdadeira, e não é mentira, como ela vos ensinou, assim nele permanecereis.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '28', 'E agora, filhinhos, permanecei nele; para que, quando ele se manifestar, tenhamos confiança, e não sejamos confundidos por ele na sua vinda.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '2', '29', 'Se sabeis que ele é justo, sabeis que todo aquele que pratica a justiça é nascido dele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '1', 'VEDE quão grande amor nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso o mundo não nos conhece; porque o não conhece a ele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '2', 'Amados, agora somos filhos de Deus, e ainda não é manifestado o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '3', 'E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '4', 'Qualquer que comete pecado, também comete iniquidade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '5', 'E bem sabeis que ele se manifestou para tirar os nossos pecados; e nele não há pecado.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '6', 'Qualquer que permanece nele não peca; qualquer que peca não o viu nem o conheceu,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '7', 'Filhinhos, ninguém vos engane. Quem pratica justiça é justo, assim como ele é justo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '8', 'Quem comete o pecado é do diabo; porque o diabo peca desde o princípio. Para isto o Filho de Deus se manifestou: para desfazer as obras do diabo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '9', 'Qualquer que é nascido de Deus não comete pecado; porque a sua semente permanece nele; e não pode pecar, porque é nascido de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '10', 'Nisto são manifestos os filhos de Deus, e os filhos do diabo. Qualquer que não pratica a justiça, e não ama a seu irmão, não é de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '11', 'Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '12', 'Não como Caim, que era do maligno, e matou a seu irmão. E por que causa o matou? Porque as suas obras eram más e as de seu irmão justas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '13', 'Meus irmãos, não vos maravilheis se o mundo vos aborrece.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '14', 'Nós sabemos que passámos da morte para a vida, porque amamos os irmãos. Quem não ama a seu irmão permanece na morte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '15', 'Qualquer que aborrece a seu irmão é homicida. E vós sabeis que nenhum homicida tem permanecente nele a vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '16', 'Conhecemos a caridade nisto que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '17', 'Quem pois tiver bens do mundo, e, vendo o seu irmão necessitado, lhe cerrar as suas entranhas, como estará nele a caridade de Deus?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '18', 'Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '19', 'E nisto conhecemos que somos da verdade, e diante dele asseguraremos nossos corações;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '20', 'Sabendo que, se o nosso coração nos condena, maior é Deus do que os nossos corações, e conhece todas as coisas.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '21', 'Amados, se o nosso coração nos não condena, temos confiança para com Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '22', 'E qualquer coisa que lhe pedirmos, dele a receberemos; porque guardamos os seus mandamentos, e fazemos o que é agradável à sua vista.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '23', 'E o seu mandamento é este: que creiamos no nome de seu Filho Jesus Cristo, e nos amemos uns aos outros, segundo o seu mandamento.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '3', '24', 'E aquele que guarda os seus mandamentos nele está, e ele nele. E nisto conhecemos que ele está em nós: pelo Espírito que nos tem');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '1', 'AMADOS, não creiais a todo o espírito, mas provai se os espíritos são de Deus; porque já muitos falsos profetas se têm levantado no mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '2', 'Nisto conhecereis o Espírito de Deus: Todo o espírito que confessa que Jesus Cristo veio em carne é de Deus;');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '3', 'E todo o espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito do anti-cristo, do qual já ouvistes que há de vir, e eis que está já no mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '4', 'Filhinhos, sois de Deus, e já os tendes vencido; porque maior é o que está em vós do que o que está no mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '5', 'Do mundo são, por isso falam do mundo, e o mundo os ouve.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '6', 'Nós somos de Deus; aquele que conhece a Deus ouve-nos; aquele que não é de Deus não nos ouve. Nisto conhecemos nós o espírito da verdade e o espírito do erro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '7', 'Amados, amemo-nos uns aos outros; porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '8', 'Aquele que não ama não conhece a Deus; porque Deus é amor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '9', 'Nisto se manifesta o amor de Deus para connosco: que Deus enviou seu Filho unigénito ao mundo, para que por ele vivamos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '10', 'Nisto está a caridade, não em que nós tenhamos amado a Deus, mas em que ele nos amou a nós, e enviou seu Filho para propiciação pelos nossos pecados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '11', 'Amados, se Deus assim nos amou, também nos devemos amar uns aos outros.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '12', 'Ninguém jamais viu a Deus; se nos amamos uns aos outros, Deus está em nós, e em nós é perfeita a sua caridade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '13', 'Nisto conhecemos que estamos nele, e ele em nós, pois que nos deu do seu Espírito,');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '14', 'E vimos, e testificamos que o Pai enviou seu Filho para Salvador do mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '15', 'Qualquer que confessar que Jesus é o Filho de Deus, Deus está nele, e ele em Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '16', 'E nós conhecemos, e cremos no amor que Deus nos tem. Deus é amor; e quem está em amor está em Deus, e Deus nele.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '17', 'Nisto é perfeito o amor para connosco, para que no dia do juízo tenhamos confiança; porque, qual ele é, somos nós também neste mundo.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '18', 'No amor não há temor, antes o perfeito amor lança fora o temor; porque o temor tem consigo a pena, e o que teme não é perfeito em amor.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '19', 'Nós o amamos a ele, porque ele nos amou primeiro.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '20', 'Se alguém diz: Eu amo a Deus, e aborrece a seu irmão, é mentiroso. Pois quem não ama a seu irmão, ao qual viu, como pode amar a Deus, a quem não viu?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '4', '21', 'E dele temos este mandamento: que quem ama a Deus, ame também a seu irmão.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '1', 'TODO aquele que crê que Jesus é o Cristo, é nascido de Deus; e todo aquele que ama ao que o gerou também ama ao que dele é nascido.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '2', 'Nisto conhecemos que amamos os filhos de Deus, quando amamos a Deus e guardamos os seus mandamentos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '3', 'Porque esta é a caridade de Deus que guardemos os seus mandamentos; e os seus mandamentos não são pesados.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '4', 'Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo, a nossa fé.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '5', 'Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '6', 'Este é aquele que veio por água e sangue, isto é, Jesus Cristo: não só por água, mas por água e por sangue. E o Espírito é o que testifica, porque o Espírito é a verdade.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '7', 'Porque três são os que testificam no céu: o Pai, a Palavra, e o Espírito Santo; e estes três são um.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '8', 'E três são os que testificam na terra: o Espírito, e a água, e o sangue; e estes três concordam num.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '9', 'Se recebemos o testemunho dos homens, o testemunho de Deus é maior; porque o testemunho de Deus é este, que de seu Filho testificou.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '10', 'Quem crê no Filho de Deus, em si mesmo tem o testemunho: quem a Deus não crê mentiroso o fez; porquanto não creu no testemunho que Deus de seu Filho deu.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '11', 'E o testemunho é este: que Deus nos deu a vida eterna; e esta vida está em seu Filho.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '12', 'Quem tem o Filho tem a vida quem não tem o Filho de Deus não tem a vida.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '13', 'Estas coisas vos escrevi, para que saibais que tendes a vida eterna, e para que creiais no nome do Filho de Deus.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '14', 'E esta é a confiança que temos nele, que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '15', 'E se sabemos que nos ouve em tudo o que pedirmos, sabemos que alcançamos as petições que lhe fizermos.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '16', 'Se alguém vir pecar seu irmão, pecado que não é para morte, orará, e Deus dará a vida àqueles que não pecarem para morte. Há pecado para morte, e por esse não digo que ore.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '17', 'Toda a iniquidade é pecado: e há pecado que não é para morte.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '18', 'Sabemos que todo aquele que é nascido de Deus não peca; mas o que de Deus é gerado conserva-se a si mesmo, e o maligno não lhe toca.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '19', 'Sabemos que somos de Deus, e que todo o mundo está no maligno.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '20', 'E sabemos que já o Filho de Deus é vindo, e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.');
INSERT INTO `bible_verses_almeida_rc` VALUES ('62', '5', '21', 'Filhinhos, guardai-vos dos ídolos. Ámen.');